#!/usr/bin/perl
$pattern=shift;
foreach (<DATA>)
{
	print $_ if($_=~/$pattern/i);
}
__DATA__
    
#2012_02_06   星期一   add by greshem
MDL（Memory Descriptor List）结构体指针
########################################################################
	227 ntoskrnl.exe.RtlInitUnicodeString
    209 ntoskrnl.exe.ExAllocatePoolWithTag #调用ExAllocatePool是从内核模式堆中分配内存的标准方式。另一个函数ExAllocatePoolWithTag
    202 ntoskrnl.exe.IofCompleteRequest		#
    185 ntoskrnl.exe.ZwClose
    185 ntoskrnl.exe.KeWaitForSingleObject
    185 ntoskrnl.exe.KeInitializeEvent
    184 ntoskrnl.exe.IoCreateDevice
    183 ntoskrnl.exe.ExFreePoolWithTag
    182 ntoskrnl.exe.IoDeleteDevice
    169 ntoskrnl.exe.KeTickCount
    169 ntoskrnl.exe.KeSetEvent
    164 ntoskrnl.exe.IofCallDriver
    163 ntoskrnl.exe.ObfDereferenceObject
    160 ntoskrnl.exe.KeBugCheckEx 			#蓝屏函数
    152 ntoskrnl.exe.KeInitializeSpinLock 	#初始化 自旋锁.
    141 ntoskrnl.exe.ZwOpenKey
    140 ntoskrnl.exe.ZwQueryValueKey
    113 ntoskrnl.exe.memmove
    110 ntoskrnl.exe._except_handler3
    108 ntoskrnl.exe._allmul
    107 ntoskrnl.exe.ObReferenceObjectByHandle
    107 ntoskrnl.exe.IoFreeMdl				#释放内存
    104 ntoskrnl.exe.IoBuildDeviceIoControlRequest
     97 ntoskrnl.exe.IoAttachDeviceToDeviceStack
     95 ntoskrnl.exe.KeInitializeDpc
     94 ntoskrnl.exe.IoDeleteSymbolicLink	#s删除链接
     92 ntoskrnl.exe.KeQuerySystemTime		#查询时间
     91 ntoskrnl.exe.wcslen
     91 ntoskrnl.exe.IoCreateSymbolicLink	#创建链接
     89 ntoskrnl.exe.RtlQueryRegistryValues
     89 ntoskrnl.exe.RtlCopyUnicodeString
     89 ntoskrnl.exe.DbgPrint
     86 ntoskrnl.exe.RtlFreeUnicodeString
     85 ntoskrnl.exe.MmMapLockedPagesSpecifyCache
     84 ntoskrnl.exe.IoReleaseCancelSpinLock
     83 ntoskrnl.exe.PoStartNextPowerIrp
     83 ntoskrnl.exe.ObfReferenceObject
     83 ntoskrnl.exe._alldiv
     82 ntoskrnl.exe.PoCallDriver
     81 ntoskrnl.exe.IoFreeIrp
     80 ntoskrnl.exe.RtlCompareMemory
     80 ntoskrnl.exe.KeDelayExecutionThread
     79 ntoskrnl.exe.KefAcquireSpinLockAtDpcLevel
     79 ntoskrnl.exe.IoAllocateMdl
     76 ntoskrnl.exe.ZwCreateFile
     76 ntoskrnl.exe.IoDetachDevice
     75 ntoskrnl.exe.ZwSetValueKey
     75 ntoskrnl.exe.KeInitializeTimer
     73 ntoskrnl.exe.KefReleaseSpinLockFromDpcLevel
     72 ntoskrnl.exe.RtlAnsiStringToUnicodeString #
     72 ntoskrnl.exe.KeSetTimer
     71 ntoskrnl.exe.IoAllocateIrp
     69 ntoskrnl.exe.IoWriteErrorLogEntry
     69 ntoskrnl.exe.IoAllocateErrorLogEntry
     66 ntoskrnl.exe.KeClearEvent
     63 ntoskrnl.exe.RtlAppendUnicodeStringToString
     63 ntoskrnl.exe.KeCancelTimer		#	
     62 ntoskrnl.exe.IoGetDeviceObjectPointer #
     61 ntoskrnl.exe.IoBuildSynchronousFsdRequest #
     60 ntoskrnl.exe.ZwCreateKey
     60 ntoskrnl.exe.RtlAppendUnicodeToString
     59 ntoskrnl.exe.swprintf
     59 ntoskrnl.exe.KeGetCurrentThread
     58 ntoskrnl.exe.PsCreateSystemThread
     58 ntoskrnl.exe.MmBuildMdlForNonPagedPool
     58 ntoskrnl.exe.ExInitializeNPagedLookasideList
     57 ntoskrnl.exe.KeLeaveCriticalRegion
     57 ntoskrnl.exe.KeEnterCriticalRegion
     57 ntoskrnl.exe._aulldiv
     56 ntoskrnl.exe.MmMapIoSpace
     55 ntoskrnl.exe.IoQueueWorkItem
     55 ntoskrnl.exe.IoFreeWorkItem
     55 ntoskrnl.exe.IoAllocateWorkItem
     55 ntoskrnl.exe.InterlockedPushEntrySList
     55 ntoskrnl.exe.InterlockedPopEntrySList
     55 ntoskrnl.exe.ExDeleteNPagedLookasideList
     54 ntoskrnl.exe.MmProbeAndLockPages
     54 ntoskrnl.exe.IoWMIRegistrationControl
     52 ntoskrnl.exe.RtlInitAnsiString
     52 ntoskrnl.exe.MmUnlockPages
     52 ntoskrnl.exe.KeInsertQueueDpc
     51 ntoskrnl.exe.PoRequestPowerIrp
     50 ntoskrnl.exe.IoGetCurrentProcess
     49 ntoskrnl.exe.MmMapLockedPages
     49 ntoskrnl.exe.ExQueueWorkItem
     48 ntoskrnl.exe.IoAcquireCancelSpinLock
     47 ntoskrnl.exe.KeResetEvent
     46 ntoskrnl.exe.MmUnmapIoSpace
     46 ntoskrnl.exe.ExInitializeResourceLite# 例程初始化一个资源变量
     46 ntoskrnl.exe.ExFreePool
     45 ntoskrnl.exe.RtlWriteRegistryValue
     44 ntoskrnl.exe.RtlEqualUnicodeString
     44 ntoskrnl.exe.PsTerminateSystemThread
     44 ntoskrnl.exe.KeQueryTimeIncrement
     43 ntoskrnl.exe.RtlUnicodeStringToAnsiString
     43 ntoskrnl.exe.IoOpenDeviceRegistryKey
     42 ntoskrnl.exe.RtlIntegerToUnicodeString
     42 ntoskrnl.exe.PoSetPowerState # 电源变化
     42 ntoskrnl.exe.ExReleaseResourceLite
     42 ntoskrnl.exe.ExDeleteResourceLite
     42 ntoskrnl.exe.ExAcquireResourceExclusiveLite
     41 ntoskrnl.exe.sprintf
     41 ntoskrnl.exe.RtlCompareUnicodeString
     41 ntoskrnl.exe.PsGetVersion
     41 ntoskrnl.exe.KeNumberProcessors #获取系统处理器的总数
     41 ntoskrnl.exe.IoGetAttachedDeviceReference
     41 ntoskrnl.exe.IoFileObjectType
     40 ntoskrnl.exe.wcscpy
     40 ntoskrnl.exe.IoSetDeviceInterfaceState
     39 ntoskrnl.exe.IoGetDeviceProperty
     38 ntoskrnl.exe.IoRegisterDeviceInterface
     38 ntoskrnl.exe.ExfInterlockedInsertTailList
     37 ntoskrnl.exe.ProbeForWrite
     37 ntoskrnl.exe.ProbeForRead
     37 ntoskrnl.exe._allshl
     36 ntoskrnl.exe._wcsnicmp
     36 ntoskrnl.exe.KeReleaseMutex #释放锁对象.
     36 ntoskrnl.exe.IoGetRelatedDeviceObject
     35 ntoskrnl.exe.IoCancelIrp
     34 ntoskrnl.exe.memset
     34 ntoskrnl.exe.KeInitializeMutex
     34 ntoskrnl.exe.DbgBreakPoint
     33 ntoskrnl.exe.ZwReadFile
     33 ntoskrnl.exe.MmLockPagableDataSection
     33 ntoskrnl.exe.ExfInterlockedRemoveHeadList
     32 ntoskrnl.exe.KeSetTimerEx
     31 ntoskrnl.exe.ZwQueryInformationFile
     31 ntoskrnl.exe.MmUnmapLockedPages
     30 ntoskrnl.exe.PsGetCurrentProcessId
     30 ntoskrnl.exe.memcpy
     29 ntoskrnl.exe.ZwWriteFile
     29 ntoskrnl.exe.ZwEnumerateKey
     29 ntoskrnl.exe._wcsicmp
     29 ntoskrnl.exe.MmGetPhysicalAddress
     29 ntoskrnl.exe.IoInvalidateDeviceRelations # driver调用IoInvalidateDeviceRelations来通知pnp manager更新他的设备树
     28 ntoskrnl.exe.RtlCreateSecurityDescriptor
     28 ntoskrnl.exe.IoConnectInterrupt
     28 ntoskrnl.exe._allshr
     27 ntoskrnl.exe.RtlSetDaclSecurityDescriptor
     26 ntoskrnl.exe.strncpy
     26 ntoskrnl.exe.strncmp
     26 ntoskrnl.exe.SeAccessCheck
     26 ntoskrnl.exe.MmUnlockPagableImageSection
     26 ntoskrnl.exe.IoGetFileObjectGenericMapping
     26 ntoskrnl.exe.ExAcquireResourceSharedLite
     25 ntoskrnl.exe.wcscat
     25 ntoskrnl.exe._stricmp
     25 ntoskrnl.exe._snwprintf
     25 ntoskrnl.exe.RtlInitString
     25 ntoskrnl.exe.KeWaitForMultipleObjects
     24 ntoskrnl.exe.RtlAddAccessAllowedAce 	#权限函数 添加权限
     24 ntoskrnl.exe.MmGetSystemRoutineAddress	#获取函数地址
     24 ntoskrnl.exe.IoWMIWriteEvent
     23 ntoskrnl.exe.ZwDeviceIoControlFile # ioctl 函数.
     23 ntoskrnl.exe.ZwDeleteKey
     23 ntoskrnl.exe.RtlLengthSid		# 返回 Sid 安全信息结构的长度.
     23 ntoskrnl.exe.KeReleaseSemaphore
     23 ntoskrnl.exe.IoRegisterShutdownNotification #系统关机的回调函数
     23 ntoskrnl.exe.IoBuildPartialMdl # IoBuildPartialMdl 分解irp成多个irp
     23 ntoskrnl.exe.InterlockedIncrement
     23 ntoskrnl.exe.ExGetPreviousMode
     22 ntoskrnl.exe.ZwOpenFile
     22 ntoskrnl.exe.RtlLengthSecurityDescriptor
     22 ntoskrnl.exe.RtlCreateAcl
     22 ntoskrnl.exe.ExCreateCallback #
     21 ntoskrnl.exe.SeExports
     21 ntoskrnl.exe.RtlUpcaseUnicodeString
     21 ntoskrnl.exe.KeSynchronizeExecution
     21 ntoskrnl.exe.KeSetPriorityThread
     21 ntoskrnl.exe.KeInitializeTimerEx
     21 ntoskrnl.exe.IoSetShareAccess
     21 ntoskrnl.exe.IoRemoveShareAccess
     21 ntoskrnl.exe.InterlockedDecrement
     21 ntoskrnl.exe.ExRegisterCallback #注册表 回调函数

     20 ntoskrnl.exe.ZwSetInformationFile
     20 ntoskrnl.exe.ZwEnumerateValueKey
     20 ntoskrnl.exe.wcsncpy
     20 ntoskrnl.exe.RtlUnicodeStringToInteger
     20 ntoskrnl.exe.RtlStringFromGUID
     20 ntoskrnl.exe.ObReferenceObjectByPointer
     20 ntoskrnl.exe.IoCheckShareAccess
     20 ntoskrnl.exe.ExSystemTimeToLocalTime
     20 ntoskrnl.exe.ExEventObjectType

     19 ntoskrnl.exe.ZwWaitForSingleObject
     19 ntoskrnl.exe.ZwQuerySystemInformation
     19 ntoskrnl.exe.wcschr
     19 ntoskrnl.exe._strnicmp
     19 ntoskrnl.exe.MmIsAddressValid
     19 ntoskrnl.exe.MmAllocateContiguousMemory
     19 ntoskrnl.exe.KeInitializeSemaphore
     19 ntoskrnl.exe.IoInitializeRemoveLockEx
     19 ntoskrnl.exe.IoGetTopLevelIrp
     19 ntoskrnl.exe.IoAllocateDriverObjectExtension
     19 ntoskrnl.exe.ExUnregisterCallback
     19 ntoskrnl.exe.ExRaiseStatus
     18 ntoskrnl.exe.wcscmp
     18 ntoskrnl.exe.SeUnlockSubjectContext
     18 ntoskrnl.exe.SeLockSubjectContext
     18 ntoskrnl.exe.RtlTimeToTimeFields
     18 ntoskrnl.exe.IoReleaseRemoveLockEx
     18 ntoskrnl.exe.IoGetRequestorProcess
     18 ntoskrnl.exe.IoGetDriverObjectExtension
     18 ntoskrnl.exe.IoDisconnectInterrupt
     18 ntoskrnl.exe.IoAcquireRemoveLockEx
     18 ntoskrnl.exe.InterlockedExchange
     18 ntoskrnl.exe.ExfInterlockedInsertHeadList
     17 ntoskrnl.exe.WRITE_REGISTER_UCHAR
     17 ntoskrnl.exe.SeSinglePrivilegeCheck
     17 ntoskrnl.exe.SeReleaseSubjectContext
     17 ntoskrnl.exe.IoReleaseRemoveLockAndWaitEx
     17 ntoskrnl.exe._aullshr
     17 ntoskrnl.exe._aullrem
     16 ntoskrnl.exe.ZwOpenSymbolicLinkObject
     16 ntoskrnl.exe.ZwLoadDriver
     16 ntoskrnl.exe._vsnprintf
     16 ntoskrnl.exe.RtlLengthRequiredSid
     16 ntoskrnl.exe.RtlInitializeSid
     16 ntoskrnl.exe.MmQuerySystemSize
     16 ntoskrnl.exe.IoSetHardErrorOrVerifyDevice
     16 ntoskrnl.exe.IoInvalidateDeviceState
     16 ntoskrnl.exe.IoGetConfigurationInformation
     15 ntoskrnl.exe.ZwDeleteValueKey
     15 ntoskrnl.exe.SeCaptureSubjectContext
     15 ntoskrnl.exe.RtlxAnsiStringToUnicodeSize
     15 ntoskrnl.exe.RtlFreeAnsiString
     15 ntoskrnl.exe.PsGetCurrentThreadId
     15 ntoskrnl.exe.NtClose
     15 ntoskrnl.exe.KeDetachProcess
     15 ntoskrnl.exe.KeAttachProcess
     15 ntoskrnl.exe.IoSetTopLevelIrp
     15 ntoskrnl.exe.IoRegisterPlugPlayNotification
     15 ntoskrnl.exe.IoInitializeIrp
     15 ntoskrnl.exe.IoGetStackLimits
     14 ntoskrnl.exe.ZwQuerySymbolicLinkObject
     14 ntoskrnl.exe.WRITE_REGISTER_USHORT
     14 ntoskrnl.exe.WRITE_REGISTER_ULONG
     14 ntoskrnl.exe.RtlCreateRegistryKey
     14 ntoskrnl.exe.READ_REGISTER_UCHAR
     14 ntoskrnl.exe.NlsMbCodePageTag
     14 ntoskrnl.exe.KeQueryActiveProcessors
     14 ntoskrnl.exe.IoStartTimer
     14 ntoskrnl.exe.IoRaiseInformationalHardError
     14 ntoskrnl.exe.IoInitializeTimer
     14 ntoskrnl.exe.IoBuildAsynchronousFsdRequest
     14 ntoskrnl.exe.FsRtlDoesNameContainWildCards
     14 ntoskrnl.exe.ExReleaseFastMutexUnsafe
     14 ntoskrnl.exe.ExAllocatePoolWithTagPriority
     14 ntoskrnl.exe.ExAllocatePoolWithQuotaTag
     14 ntoskrnl.exe.ExAcquireFastMutexUnsafe
     13 ntoskrnl.exe.ZwMapViewOfSection
     13 ntoskrnl.exe.ZwCreateDirectoryObject
     13 ntoskrnl.exe.wcsstr
     13 ntoskrnl.exe.strstr
     13 ntoskrnl.exe.SeSetSecurityDescriptorInfo
     13 ntoskrnl.exe.SeAssignSecurity
     13 ntoskrnl.exe.RtlSubAuthoritySid
     13 ntoskrnl.exe.READ_REGISTER_USHORT
     13 ntoskrnl.exe.ObQueryNameString
     13 ntoskrnl.exe.ObOpenObjectByPointer
     13 ntoskrnl.exe.MmUserProbeAddress
     13 ntoskrnl.exe.KeRemoveQueueDpc
     13 ntoskrnl.exe.IoUnregisterPlugPlayNotification
     13 ntoskrnl.exe.IoIsOperationSynchronous
     13 ntoskrnl.exe.IoCreateFile
     13 ntoskrnl.exe.FsRtlIsNameInExpression
     12 ntoskrnl.exe.ZwUnmapViewOfSection
     12 ntoskrnl.exe.ZwPowerInformation
     12 ntoskrnl.exe._vsnwprintf
     12 ntoskrnl.exe.RtlUpcaseUnicodeChar
     12 ntoskrnl.exe.RtlUnwind
     12 ntoskrnl.exe.RtlSetOwnerSecurityDescriptor
     12 ntoskrnl.exe.RtlGetDaclSecurityDescriptor
     12 ntoskrnl.exe.READ_REGISTER_ULONG
     12 ntoskrnl.exe.MmFreeContiguousMemory
     12 ntoskrnl.exe.MmFlushImageSection
     12 ntoskrnl.exe.KeUnstackDetachProcess
     12 ntoskrnl.exe.KeStackAttachProcess
     12 ntoskrnl.exe.KeReadStateEvent
     12 ntoskrnl.exe.KeQueryInterruptTime
     12 ntoskrnl.exe.ExInterlockedPopEntrySList
     12 ntoskrnl.exe.ExfInterlockedAddUlong
     11 ntoskrnl.exe.ZwCreateSection
     11 ntoskrnl.exe.ZwCreateEvent
     11 ntoskrnl.exe.strchr
     11 ntoskrnl.exe.SeFreePrivileges
     11 ntoskrnl.exe.RtlTimeFieldsToTime
     11 ntoskrnl.exe.RtlMapGenericMask
     11 ntoskrnl.exe.RtlInitializeBitMap
     11 ntoskrnl.exe.RtlDeleteRegistryValue
     11 ntoskrnl.exe.RtlClearBits
     11 ntoskrnl.exe.RtlCheckRegistryKey
     11 ntoskrnl.exe.RtlAbsoluteToSelfRelativeSD
     11 ntoskrnl.exe.PsGetCurrentThread
     11 ntoskrnl.exe.PsGetCurrentProcess
     11 ntoskrnl.exe.IoStopTimer
     11 ntoskrnl.exe.IoRegisterFileSystem #注册文件系统  ext2fsd 用过东风恶.
     11 ntoskrnl.exe.IoGetDmaAdapter
     11 ntoskrnl.exe.InterlockedCompareExchange
     11 ntoskrnl.exe.FsRtlIsNtstatusExpected
     11 ntoskrnl.exe.FsRtlFastUnlockAll
     11 ntoskrnl.exe.ExInterlockedPushEntrySList
     11 ntoskrnl.exe.ExInterlockedAddLargeStatistic
     11 ntoskrnl.exe.ExAllocatePool
     11 ntoskrnl.exe.CcUninitializeCacheMap
     11 ntoskrnl.exe.CcSetFileSizes
     11 ntoskrnl.exe.CcPurgeCacheSection
     11 ntoskrnl.exe.CcCopyRead
     11 ntoskrnl.exe._abnormal_termination
     10 ntoskrnl.exe.wcsrchr
     10 ntoskrnl.exe.wcsncmp
     10 ntoskrnl.exe._snprintf
     10 ntoskrnl.exe.SeAppendPrivileges
     10 ntoskrnl.exe.RtlGetOwnerSecurityDescriptor
     10 ntoskrnl.exe.PsSetCreateProcessNotifyRoutine # 当有进程创建的时候，就会调用这个NotifyRoutine对应的函数
     10 ntoskrnl.exe.PsLookupProcessByProcessId
     10 ntoskrnl.exe.MmPageEntireDriver
     10 ntoskrnl.exe._local_unwind2
     10 ntoskrnl.exe.KeBugCheck
     10 ntoskrnl.exe.IoUnregisterShutdownNotification
     10 ntoskrnl.exe.IoReuseIrp
     10 ntoskrnl.exe.IoReleaseVpbSpinLock
     10 ntoskrnl.exe.IoAcquireVpbSpinLock
     10 ntoskrnl.exe.FsRtlProcessFileLock #文件锁操作 
     10 ntoskrnl.exe.FsRtlNormalizeNtstatus
     10 ntoskrnl.exe.ExReleaseResourceForThreadLite
     10 ntoskrnl.exe.ExRaiseAccessViolation
     10 ntoskrnl.exe.CcMdlReadComplete
     10 ntoskrnl.exe.CcMdlRead
     10 ntoskrnl.exe.CcInitializeCacheMap
     10 ntoskrnl.exe._aulldvrm
     10 ntoskrnl.exe._allrem
      9 ntoskrnl.exe.ZwSetSecurityObject
      9 ntoskrnl.exe.ZwQueryKey
      9 ntoskrnl.exe.ZwOpenDirectoryObject
      9 ntoskrnl.exe.ZwFsControlFile
      9 ntoskrnl.exe.vsprintf
      9 ntoskrnl.exe.VerSetConditionMask
      9 ntoskrnl.exe.strrchr
      9 ntoskrnl.exe.SeValidSecurityDescriptor
      9 ntoskrnl.exe.SeDeassignSecurity
      9 ntoskrnl.exe.RtlVerifyVersionInfo
      9 ntoskrnl.exe.RtlSplay
      9 ntoskrnl.exe.RtlSetGroupSecurityDescriptor
      9 ntoskrnl.exe.RtlSetBits
      9 ntoskrnl.exe.RtlGUIDFromString
      9 ntoskrnl.exe.RtlDelete
      9 ntoskrnl.exe.PsThreadType
      9 ntoskrnl.exe.ObReleaseObjectSecurity
      9 ntoskrnl.exe.ObGetObjectSecurity
      9 ntoskrnl.exe.NtCreateFile
      9 ntoskrnl.exe.MmCanFileBeTruncated
      9 ntoskrnl.exe.IoStartPacket
      9 ntoskrnl.exe.IoRegisterDriverReinitialization
      9 ntoskrnl.exe.IoRegisterBootDriverReinitialization
      9 ntoskrnl.exe.IoQueryDeviceDescription
      9 ntoskrnl.exe.IoIsWdmVersionAvailable
      9 ntoskrnl.exe.FsRtlTeardownPerStreamContexts
      9 ntoskrnl.exe.FsRtlFastUnlockSingle
      9 ntoskrnl.exe.FsRtlFastCheckLockForRead
      9 ntoskrnl.exe.FsRtlCheckLockForReadAccess
      9 ntoskrnl.exe.ExUuidCreate
      9 ntoskrnl.exe.ExIsResourceAcquiredExclusiveLite
      9 ntoskrnl.exe.ExAcquireSharedStarveExclusive
      9 ntoskrnl.exe.CcSetReadAheadGranularity
      9 ntoskrnl.exe.CcFlushCache
      8 ntoskrnl.exe.ZwSetInformationThread # ZwSetInformationThread 可以用来将线程隐藏，从而使调试器接收不到信息
      8 ntoskrnl.exe.ZwQueryDirectoryFile	#获取文件系统 有 基于这个函数上的 文件隐藏的运用.
      8 ntoskrnl.exe.WmiTraceMessage
      8 ntoskrnl.exe._wcsupr
      8 ntoskrnl.exe.strlen
      8 ntoskrnl.exe.SeQueryAuthenticationIdToken
      8 ntoskrnl.exe.RtlPrefixUnicodeString
      8 ntoskrnl.exe.RtlFreeOemString
      8 ntoskrnl.exe.RtlEqualString
      8 ntoskrnl.exe._purecall
      8 ntoskrnl.exe.PoUnregisterSystemState
      8 ntoskrnl.exe.PoRegisterSystemState
      8 ntoskrnl.exe.MmSizeOfMdl
      8 ntoskrnl.exe.MmIsThisAnNtAsSystem
      8 ntoskrnl.exe.KeSetSystemAffinityThread
      8 ntoskrnl.exe.KeServiceDescriptorTable
      8 ntoskrnl.exe.KeSaveFloatingPointState
      8 ntoskrnl.exe.KeRevertToUserAffinityThread
      8 ntoskrnl.exe.KeRestoreFloatingPointState
      8 ntoskrnl.exe.isdigit
      8 ntoskrnl.exe.IoUpdateShareAccess
      8 ntoskrnl.exe.IoUnregisterFileSystem #注销文件系统
      8 ntoskrnl.exe.IoStartNextPacket  # 以使驱动程序的StartIo例程被设备队列中下一个IRP调用
      8 ntoskrnl.exe.IoReportTargetDeviceChangeAsynchronous
      8 ntoskrnl.exe.IoReportDetectedDevice #对于非即插即用设备，驱动程序通过调用 这个函数 向PnP管理器报告此设备
      8 ntoskrnl.exe.IoRegisterFsRegistrationChange
      8 ntoskrnl.exe.IoGetDeviceInterfaces
      8 ntoskrnl.exe.InitSafeBootMode 		#系统的 运行的模式.
      8 ntoskrnl.exe.FsRtlUninitializeFileLock
      8 ntoskrnl.exe.FsRtlNotifyInitializeSync
      8 ntoskrnl.exe.FsRtlInitializeFileLock
      8 ntoskrnl.exe.FsRtlFastCheckLockForWrite
      8 ntoskrnl.exe.ExIsResourceAcquiredSharedLite
      8 ntoskrnl.exe.ExAcquireSharedWaitForExclusive
      7 ntoskrnl.exe.ZwQueryVolumeInformationFile
      7 ntoskrnl.exe.ZwQueryInformationProcess
      7 ntoskrnl.exe.ZwMakeTemporaryObject
      7 ntoskrnl.exe.ZwFreeVirtualMemory
      7 ntoskrnl.exe.ZwFlushKey
      7 ntoskrnl.exe.WmiQueryTraceInformation
      7 ntoskrnl.exe.RtlUnicodeToMultiByteN
      7 ntoskrnl.exe.RtlRaiseException
      7 ntoskrnl.exe.RtlMultiByteToUnicodeN
      7 ntoskrnl.exe.RtlGetSaclSecurityDescriptor
      7 ntoskrnl.exe.RtlGetGroupSecurityDescriptor
      7 ntoskrnl.exe.RtlGetCallersAddress
      7 ntoskrnl.exe.RtlExtendedMagicDivide
      7 ntoskrnl.exe.RtlClearAllBits
      7 ntoskrnl.exe.PsProcessType
      7 ntoskrnl.exe.PsInitialSystemProcess
      7 ntoskrnl.exe.ObReferenceObjectByName
      7 ntoskrnl.exe.NlsMbOemCodePageTag
      7 ntoskrnl.exe.MmResetDriverPaging
      7 ntoskrnl.exe.MmHighestUserAddress
      7 ntoskrnl.exe.KeSetTargetProcessorDpc
      7 ntoskrnl.exe.FsRtlUninitializeOplock
      7 ntoskrnl.exe.FsRtlOplockIsFastIoPossible
      7 ntoskrnl.exe.FsRtlOplockFsctrl
      7 ntoskrnl.exe.FsRtlNotifyUninitializeSync
      7 ntoskrnl.exe.FsRtlNotifyFullChangeDirectory
      7 ntoskrnl.exe.FsRtlNotifyCleanup
      7 ntoskrnl.exe.FsRtlLegalAnsiCharacterArray #
      7 ntoskrnl.exe.FsRtlIsFatDbcsLegal
      7 ntoskrnl.exe.FsRtlCurrentBatchOplock #
      7 ntoskrnl.exe.FsRtlCheckOplock
      7 ntoskrnl.exe.FsRtlCheckLockForWriteAccess
      7 ntoskrnl.exe.ExInitializePagedLookasideList
      7 ntoskrnl.exe.CcZeroData
      7 ntoskrnl.exe.CcWaitForCurrentLazyWriterActivity
      7 ntoskrnl.exe.CcPrepareMdlWrite
      7 ntoskrnl.exe.CcMdlWriteComplete
      7 ntoskrnl.exe.CcDeferWrite
      7 ntoskrnl.exe.CcCopyWrite
      7 ntoskrnl.exe.CcCanIWrite
      6 ntoskrnl.exe.ZwUnloadDriver
      6 ntoskrnl.exe.ZwAllocateVirtualMemory
      6 ntoskrnl.exe.toupper
      6 ntoskrnl.exe.tolower
      6 ntoskrnl.exe.SeQuerySecurityDescriptorInfo
      6 ntoskrnl.exe.SeQueryInformationToken
      6 ntoskrnl.exe.RtlVolumeDeviceToDosName
      6 ntoskrnl.exe.RtlUnicodeStringToOemString
      6 ntoskrnl.exe.RtlUnicodeStringToCountedOemString
      6 ntoskrnl.exe.RtlInsertElementGenericTable
      6 ntoskrnl.exe.RtlInitializeGenericTable
      6 ntoskrnl.exe.RtlExtendedIntegerMultiply
      6 ntoskrnl.exe.RtlEqualSid
      6 ntoskrnl.exe.RtlDeleteElementGenericTable
      6 ntoskrnl.exe.RtlCompareString
      6 ntoskrnl.exe.ObSetSecurityObjectByPointer
      6 ntoskrnl.exe.NtDeviceIoControlFile
      6 ntoskrnl.exe.NtBuildNumber		#内核版本号.
      6 ntoskrnl.exe.MmAllocatePagesForMdl
      6 ntoskrnl.exe.MmAllocateContiguousMemorySpecifyCache
      6 ntoskrnl.exe.KeSetImportanceDpc
      6 ntoskrnl.exe.KeSetAffinityThread
      6 ntoskrnl.exe.KeRemoveQueue
      6 ntoskrnl.exe.KeInsertQueue
      6 ntoskrnl.exe.KeInitializeQueue
      6 ntoskrnl.exe.KeGetRecommendedSharedDataAlignment
      6 ntoskrnl.exe.IoSetDeviceToVerify
      6 ntoskrnl.exe.IoMakeAssociatedIrp
      6 ntoskrnl.exe.IoGetDeviceAttachmentBaseRef
      6 ntoskrnl.exe.IoCreateUnprotectedSymbolicLink
      6 ntoskrnl.exe.IoCheckEaBufferValidity
      6 ntoskrnl.exe.HalDispatchTable
      6 ntoskrnl.exe.FsRtlPrivateLock
      6 ntoskrnl.exe.FsRtlPostStackOverflow
      6 ntoskrnl.exe.FsRtlFastUnlockAllByKey
      6 ntoskrnl.exe.FsRtlCopyRead
      6 ntoskrnl.exe.FsRtlAreNamesEqual
      6 ntoskrnl.exe.ExSetTimerResolution
      6 ntoskrnl.exe.ExLocalTimeToSystemTime
      6 ntoskrnl.exe.ExConvertExclusiveToSharedLite
      6 ntoskrnl.exe.CcUnpinData
      6 ntoskrnl.exe._alldvrm
      5 ntoskrnl.exe.ZwOpenSection
      5 ntoskrnl.exe.ZwOpenEvent
      5 ntoskrnl.exe.wcsncat
      5 ntoskrnl.exe.SeTokenType
      5 ntoskrnl.exe.SeQuerySessionIdToken
      5 ntoskrnl.exe.SeOpenObjectAuditAlarm
      5 ntoskrnl.exe.SeCaptureSecurityDescriptor
      5 ntoskrnl.exe.RtlOemStringToUnicodeString
      5 ntoskrnl.exe.RtlLookupElementGenericTable
      5 ntoskrnl.exe.RtlGetAce
      5 ntoskrnl.exe.RtlGenerate8dot3Name
      5 ntoskrnl.exe.RtlFindClearBits
      5 ntoskrnl.exe.RtlExtendedLargeIntegerDivide
      5 ntoskrnl.exe.RtlEnumerateGenericTableWithoutSplaying
      5 ntoskrnl.exe.RtlCreateUnicodeString
      5 ntoskrnl.exe.PsSetLoadImageNotifyRoutine
      5 ntoskrnl.exe.PsIsThreadTerminating
      5 ntoskrnl.exe.ObInsertObject
      5 ntoskrnl.exe.NtSetInformationFile
      5 ntoskrnl.exe.NtQueryInformationFile
      5 ntoskrnl.exe.NlsOemLeadByteInfo
      5 ntoskrnl.exe.MmLockPagableSectionByHandle
      5 ntoskrnl.exe.MmFreePagesFromMdl
      5 ntoskrnl.exe.MmCreateMdl
      5 ntoskrnl.exe.KeRundownQueue
      5 ntoskrnl.exe.IoVerifyVolume
      5 ntoskrnl.exe.IoSetThreadHardErrorMode
      5 ntoskrnl.exe.IoSetCompletionRoutineEx
      5 ntoskrnl.exe.IoRaiseHardError
      5 ntoskrnl.exe.IoOpenDeviceInterfaceRegistryKey
      5 ntoskrnl.exe.IoGetDeviceToVerify
      5 ntoskrnl.exe.IoDriverObjectType
      5 ntoskrnl.exe.IoDeviceObjectType
      5 ntoskrnl.exe.IoCreateStreamFileObject
      5 ntoskrnl.exe.IoCreateNotificationEvent
      5 ntoskrnl.exe.FsRtlUninitializeLargeMcb
      5 ntoskrnl.exe.FsRtlTruncateLargeMcb
      5 ntoskrnl.exe.FsRtlNotifyVolumeEvent
      5 ntoskrnl.exe.FsRtlNotifyFullReportChange
      5 ntoskrnl.exe.FsRtlLookupLargeMcbEntry
      5 ntoskrnl.exe.FsRtlIsTotalDeviceFailure
      5 ntoskrnl.exe.FsRtlInitializeOplock
      5 ntoskrnl.exe.FsRtlInitializeLargeMcb
      5 ntoskrnl.exe.FsRtlAddLargeMcbEntry
      5 ntoskrnl.exe.ExRaiseDatatypeMisalignment
      5 ntoskrnl.exe.ExNotifyCallback
      5 ntoskrnl.exe.ExfInterlockedPushEntryList
      5 ntoskrnl.exe.ExDeletePagedLookasideList
      5 ntoskrnl.exe.CcSetAdditionalCacheAttributes
      5 ntoskrnl.exe.CcMapData
########################################################################
      4 ntoskrnl.exe.CcFastCopyRead
      4 ntoskrnl.exe.CcFastCopyWrite
      4 ntoskrnl.exe.CcPinRead
      4 ntoskrnl.exe.CcSetDirtyPinnedData
      4 ntoskrnl.exe.DbgPrintEx
      4 ntoskrnl.exe.ExInterlockedAddLargeInteger
      4 ntoskrnl.exe.ExInterlockedFlushSList
      4 ntoskrnl.exe.ExSetResourceOwnerPointer
      4 ntoskrnl.exe.FsRtlAllocateFileLock
      4 ntoskrnl.exe.FsRtlDeregisterUncProvider
      4 ntoskrnl.exe.FsRtlDissectName
      4 ntoskrnl.exe.FsRtlFreeFileLock
      4 ntoskrnl.exe.FsRtlMdlReadCompleteDev
      4 ntoskrnl.exe.FsRtlMdlWriteCompleteDev
      4 ntoskrnl.exe.FsRtlRegisterUncProvider
      4 ntoskrnl.exe.FsRtlRemoveLargeMcbEntry
      4 ntoskrnl.exe.IoAssignResources
      4 ntoskrnl.exe.IoGetAttachedDevice
      4 ntoskrnl.exe.IoGetBaseFileSystemDeviceObject #文件系统的基类?
      4 ntoskrnl.exe.IoGetRequestorSessionId
      4 ntoskrnl.exe.IoIsSystemThread
      4 ntoskrnl.exe.IoReadPartitionTableEx
      4 ntoskrnl.exe.IoReportResourceForDetection
      4 ntoskrnl.exe.IoThreadToProcess
      4 ntoskrnl.exe.IoUnregisterFsRegistrationChange
      4 ntoskrnl.exe.KdDebuggerEnabled
      4 ntoskrnl.exe.KeFlushQueuedDpcs
      4 ntoskrnl.exe.KeReadStateMutex
      4 ntoskrnl.exe.KeReadStateTimer
      4 ntoskrnl.exe.LsaFreeReturnBuffer
      4 ntoskrnl.exe.MmAllocateMappingAddress
      4 ntoskrnl.exe.MmForceSectionClosed
      4 ntoskrnl.exe.MmFreeContiguousMemorySpecifyCache
      4 ntoskrnl.exe.MmFreeMappingAddress
      4 ntoskrnl.exe.MmIsVerifierEnabled
      4 ntoskrnl.exe.MmMapLockedPagesWithReservedMapping #
      4 ntoskrnl.exe.MmUnmapReservedMapping
      4 ntoskrnl.exe.NtOpenFile
      4 ntoskrnl.exe.NtWaitForSingleObject
      4 ntoskrnl.exe.ObCloseHandle
      4 ntoskrnl.exe.ObCreateObject
      4 ntoskrnl.exe.PsDereferenceImpersonationToken
      4 ntoskrnl.exe.PsDereferencePrimaryToken
      4 ntoskrnl.exe.PsGetProcessId
      4 ntoskrnl.exe.PsRevertToSelf
      4 ntoskrnl.exe.READ_REGISTER_BUFFER_UCHAR
      4 ntoskrnl.exe.READ_REGISTER_BUFFER_ULONG
      4 ntoskrnl.exe.RtlAreBitsSet
      4 ntoskrnl.exe.RtlCopySid
      4 ntoskrnl.exe.RtlFindClearBitsAndSet
      4 ntoskrnl.exe.RtlFindUnicodePrefix
      4 ntoskrnl.exe.RtlGetVersion
      4 ntoskrnl.exe.RtlInitializeUnicodePrefix
      4 ntoskrnl.exe.RtlInsertUnicodePrefix
      4 ntoskrnl.exe.RtlIpv4StringToAddressW
      4 ntoskrnl.exe.RtlNumberOfClearBits
      4 ntoskrnl.exe.RtlOemStringToCountedUnicodeString
      4 ntoskrnl.exe.RtlOemToUnicodeN
      4 ntoskrnl.exe.RtlRandom
      4 ntoskrnl.exe.RtlRemoveUnicodePrefix
      4 ntoskrnl.exe.RtlUpcaseUnicodeStringToOemString
      4 ntoskrnl.exe.RtlValidSid
      4 ntoskrnl.exe.RtlxOemStringToUnicodeSize
      4 ntoskrnl.exe.RtlxUnicodeStringToOemSize
      4 ntoskrnl.exe.SeCreateAccessState
      4 ntoskrnl.exe.SeCreateClientSecurity
      4 ntoskrnl.exe.SeTokenIsRestricted
      4 ntoskrnl.exe.ZwDuplicateObject
      4 ntoskrnl.exe.ZwOpenProcess
      4 ntoskrnl.exe.ZwQueryObject
      4 ntoskrnl.exe.ZwYieldExecution
      4 ntoskrnl.exe.atoi
      4 ntoskrnl.exe.isspace
      4 ntoskrnl.exe.isupper
      4 ntoskrnl.exe.rand
      4 ntoskrnl.exe.strcpy

########################################################################
      3 ntoskrnl.exe.CcPinMappedData
      3 ntoskrnl.exe.ExGetExclusiveWaiterCount
      3 ntoskrnl.exe.ExInitializeZone
      3 ntoskrnl.exe.ExInterlockedRemoveHeadList
      3 ntoskrnl.exe.ExfInterlockedCompareExchange64
      3 ntoskrnl.exe.ExfInterlockedPopEntryList
      3 ntoskrnl.exe.FsRtlAddToTunnelCache
      3 ntoskrnl.exe.FsRtlBalanceReads
      3 ntoskrnl.exe.FsRtlCopyWrite
      3 ntoskrnl.exe.FsRtlDeleteKeyFromTunnelCache
      3 ntoskrnl.exe.FsRtlDeleteTunnelCache
      3 ntoskrnl.exe.FsRtlFindInTunnelCache
      3 ntoskrnl.exe.FsRtlGetNextLargeMcbEntry
      3 ntoskrnl.exe.FsRtlInitializeTunnelCache
      3 ntoskrnl.exe.FsRtlMdlReadDev
      3 ntoskrnl.exe.FsRtlNumberOfRunsInLargeMcb
      3 ntoskrnl.exe.FsRtlPostPagingFileStackOverflow
      3 ntoskrnl.exe.FsRtlPrepareMdlWriteDev
      3 ntoskrnl.exe.FsRtlRegisterFileSystemFilterCallbacks
      3 ntoskrnl.exe.IoCreateController
      3 ntoskrnl.exe.IoDeleteController
      3 ntoskrnl.exe.IoFreeErrorLogEntry
      3 ntoskrnl.exe.IoGetLowerDeviceObject
      3 ntoskrnl.exe.IoVolumeDeviceToDosName
      3 ntoskrnl.exe.KeAcquireSpinLockRaiseToDpc
      3 ntoskrnl.exe.KeDeregisterBugCheckCallback
      3 ntoskrnl.exe.KeDeregisterBugCheckReasonCallback
      3 ntoskrnl.exe.KeInitializeApc
      3 ntoskrnl.exe.KeInsertQueueApc
      3 ntoskrnl.exe.KeRegisterBugCheckCallback
      3 ntoskrnl.exe.KeRegisterBugCheckReasonCallback
      3 ntoskrnl.exe.KeReleaseSpinLock
      3 ntoskrnl.exe.Mm64BitPhysicalAddress
      3 ntoskrnl.exe.MmAddVerifierThunks
      3 ntoskrnl.exe.MmMapViewOfSection
      3 ntoskrnl.exe.MmSystemRangeStart
      3 ntoskrnl.exe.NtQueryVolumeInformationFile
      3 ntoskrnl.exe.NtReadFile
      3 ntoskrnl.exe.NtSetInformationThread
      3 ntoskrnl.exe.NtWriteFile
      3 ntoskrnl.exe.ObDereferenceSecurityDescriptor
      3 ntoskrnl.exe.ObLogSecurityDescriptor
      3 ntoskrnl.exe.PoRegisterDeviceForIdleDetection
      3 ntoskrnl.exe.PoSetSystemState
      3 ntoskrnl.exe.PsImpersonateClient
      3 ntoskrnl.exe.READ_REGISTER_BUFFER_USHORT
      3 ntoskrnl.exe.RtlAddRange
      3 ntoskrnl.exe.RtlAreBitsClear
      3 ntoskrnl.exe.RtlCopyRangeList
      3 ntoskrnl.exe.RtlDeleteElementGenericTableAvl
      3 ntoskrnl.exe.RtlDeleteOwnersRanges
      3 ntoskrnl.exe.RtlDeleteRange
      3 ntoskrnl.exe.RtlFindMessage
      3 ntoskrnl.exe.RtlFindNextForwardRunClear
      3 ntoskrnl.exe.RtlFindRange
      3 ntoskrnl.exe.RtlFreeRangeList
      3 ntoskrnl.exe.RtlGetCompressionWorkSpaceSize
      3 ntoskrnl.exe.RtlGetFirstRange
      3 ntoskrnl.exe.RtlGetNextRange
      3 ntoskrnl.exe.RtlImageDirectoryEntryToData
      3 ntoskrnl.exe.RtlImageNtHeader
      3 ntoskrnl.exe.RtlInitializeGenericTableAvl
      3 ntoskrnl.exe.RtlInitializeRangeList
      3 ntoskrnl.exe.RtlInsertElementGenericTableFullAvl
      3 ntoskrnl.exe.RtlIsNameLegalDOS8Dot3
      3 ntoskrnl.exe.RtlLookupElementGenericTableFullAvl
      3 ntoskrnl.exe.RtlNtStatusToDosError
      3 ntoskrnl.exe.RtlNtStatusToDosErrorNoTeb
      3 ntoskrnl.exe.RtlNumberGenericTableElements
      3 ntoskrnl.exe.RtlSecondsSince1970ToTime
      3 ntoskrnl.exe.RtlSelfRelativeToAbsoluteSD
      3 ntoskrnl.exe.RtlSetBit
      3 ntoskrnl.exe.RtlTimeToSecondsSince1970
      3 ntoskrnl.exe.RtlUnicodeToOemN
      3 ntoskrnl.exe.RtlUpcaseUnicodeToOemN
      3 ntoskrnl.exe.RtlValidRelativeSecurityDescriptor
      3 ntoskrnl.exe.RtlValidSecurityDescriptor
      3 ntoskrnl.exe.SeImpersonateClientEx
      3 ntoskrnl.exe.SePrivilegeCheck #
      3 ntoskrnl.exe.WRITE_REGISTER_BUFFER_UCHAR
      3 ntoskrnl.exe.WRITE_REGISTER_BUFFER_ULONG
      3 ntoskrnl.exe.WRITE_REGISTER_BUFFER_USHORT
      3 ntoskrnl.exe.ZwDeleteFile
      3 ntoskrnl.exe.ZwQuerySecurityObject
      3 ntoskrnl.exe.ZwTerminateProcess
      3 ntoskrnl.exe.__C_specific_handler
      3 ntoskrnl.exe._strlwr
      3 ntoskrnl.exe.isxdigit
      3 ntoskrnl.exe.mbstowcs
      3 ntoskrnl.exe.memchr
      3 ntoskrnl.exe.qsort

########################################################################

      2 ntoskrnl.exe.CcGetFileObjectFromBcb
      2 ntoskrnl.exe.CcIsThereDirtyData
      2 ntoskrnl.exe.CcMdlWriteAbort
      2 ntoskrnl.exe.CcPreparePinWrite
      2 ntoskrnl.exe.CcRepinBcb
      2 ntoskrnl.exe.CcUnpinRepinnedBcb
      2 ntoskrnl.exe.DbgBreakPointWithStatus
      2 ntoskrnl.exe.DbgPrompt
      2 ntoskrnl.exe.ExAcquireFastMutex
      2 ntoskrnl.exe.ExExtendZone
      2 ntoskrnl.exe.ExGetSharedWaiterCount
      2 ntoskrnl.exe.ExInterlockedInsertTailList
      2 ntoskrnl.exe.ExIsProcessorFeaturePresent
      2 ntoskrnl.exe.ExQueryDepthSList
      2 ntoskrnl.exe.ExReleaseFastMutex
      2 ntoskrnl.exe.ExVerifySuite
      2 ntoskrnl.exe.ExpInterlockedPopEntrySList
      2 ntoskrnl.exe.ExpInterlockedPushEntrySList
      2 ntoskrnl.exe.FsRtlGetNextFileLock
      2 ntoskrnl.exe.FsRtlLookupLastLargeMcbEntryAndIndex
      2 ntoskrnl.exe.FsRtlNotifyFilterChangeDirectory
      2 ntoskrnl.exe.FsRtlResetLargeMcb
      2 ntoskrnl.exe.HalExamineMBR
      2 ntoskrnl.exe.HeadlessDispatch
      2 ntoskrnl.exe.InterlockedExchangeAdd
      2 ntoskrnl.exe.IoAllocateAdapterChannel
      2 ntoskrnl.exe.IoAllocateController
      2 ntoskrnl.exe.IoAttachDevice
      2 ntoskrnl.exe.IoCreateFileSpecifyDeviceObjectHint
      2 ntoskrnl.exe.IoCreateSynchronizationEvent
      2 ntoskrnl.exe.IoCsqInitialize
      2 ntoskrnl.exe.IoCsqInsertIrp
      2 ntoskrnl.exe.IoCsqRemoveIrp
      2 ntoskrnl.exe.IoEnumerateDeviceObjectList
      2 ntoskrnl.exe.IoFreeController
      2 ntoskrnl.exe.IoGetBootDiskInformation
      2 ntoskrnl.exe.IoGetDiskDeviceObject #获取 由一个文件系统关联的磁盘设备.
      2 ntoskrnl.exe.IoQueueThreadIrp
      2 ntoskrnl.exe.IoReportResourceUsage
      2 ntoskrnl.exe.IoRequestDeviceEject
      2 ntoskrnl.exe.IoSetInformation
      2 ntoskrnl.exe.IoSetIoCompletion
      2 ntoskrnl.exe.IoSetStartIoAttributes
      2 ntoskrnl.exe.IoSetSystemPartition
      2 ntoskrnl.exe.IoWMIOpenBlock
      2 ntoskrnl.exe.IoWMIQueryAllData
      2 ntoskrnl.exe.IoWritePartitionTableEx
      2 ntoskrnl.exe.KdDebuggerNotPresent
      2 ntoskrnl.exe.KdDisableDebugger
      2 ntoskrnl.exe.KdEnableDebugger
      2 ntoskrnl.exe.KeAddSystemServiceTable
      2 ntoskrnl.exe.KeInsertByKeyDeviceQueue
      2 ntoskrnl.exe.KeLoaderBlock
      2 ntoskrnl.exe.KeReadStateSemaphore
      2 ntoskrnl.exe.KeRemoveDeviceQueue
      2 ntoskrnl.exe.KeSetBasePriorityThread
      2 ntoskrnl.exe.KiIpiServiceRoutine
      2 ntoskrnl.exe.LdrAccessResource
      2 ntoskrnl.exe.LdrFindResource_U
      2 ntoskrnl.exe.MmAllocateNonCachedMemory
      2 ntoskrnl.exe.MmCreateSection
      2 ntoskrnl.exe.MmFreeNonCachedMemory
      2 ntoskrnl.exe.MmGetPhysicalMemoryRanges
      2 ntoskrnl.exe.MmIsDriverVerifying
      2 ntoskrnl.exe.MmIsNonPagedSystemAddressValid
      2 ntoskrnl.exe.MmProbeAndLockProcessPages
      2 ntoskrnl.exe.MmSectionObjectType
      2 ntoskrnl.exe.MmSecureVirtualMemory
      2 ntoskrnl.exe.MmUnmapViewOfSection
      2 ntoskrnl.exe.MmUnsecureVirtualMemory
      2 ntoskrnl.exe.NtQuerySystemInformation
      2 ntoskrnl.exe.NtSetSecurityObject
      2 ntoskrnl.exe.ObMakeTemporaryObject
      2 ntoskrnl.exe.ObOpenObjectByName
      2 ntoskrnl.exe.PsAssignImpersonationToken
      2 ntoskrnl.exe.PsChargeProcessPoolQuota
      2 ntoskrnl.exe.PsGetCurrentProcessSessionId
      2 ntoskrnl.exe.PsGetProcessImageFileName
      2 ntoskrnl.exe.PsGetThreadHardErrorsAreDisabled
      2 ntoskrnl.exe.PsGetThreadProcessId
      2 ntoskrnl.exe.PsReferenceImpersonationToken
      2 ntoskrnl.exe.PsReturnPoolQuota
      2 ntoskrnl.exe.PsSetThreadHardErrorsAreDisabled
      2 ntoskrnl.exe.RtlAddAccessAllowedAceEx
      2 ntoskrnl.exe.RtlAddAce
      2 ntoskrnl.exe.RtlAllocateHeap
      2 ntoskrnl.exe.RtlAppendStringToString
      2 ntoskrnl.exe.RtlCompressBuffer
      2 ntoskrnl.exe.RtlCreateHeap
      2 ntoskrnl.exe.RtlCreateSystemVolumeInformationFolder
      2 ntoskrnl.exe.RtlCustomCPToUnicodeN
      2 ntoskrnl.exe.RtlDecompressFragment
      2 ntoskrnl.exe.RtlDeleteAce
      2 ntoskrnl.exe.RtlDestroyHeap
      2 ntoskrnl.exe.RtlEnumerateGenericTable
      2 ntoskrnl.exe.RtlEnumerateGenericTableAvl
      2 ntoskrnl.exe.RtlFindClearRuns
      2 ntoskrnl.exe.RtlFindLongestRunClear
      2 ntoskrnl.exe.RtlFreeHeap
      2 ntoskrnl.exe.RtlGetDefaultCodePage
      2 ntoskrnl.exe.RtlInitCodePageTable
      2 ntoskrnl.exe.RtlInsertElementGenericTableAvl
      2 ntoskrnl.exe.RtlIpv4AddressToStringA
      2 ntoskrnl.exe.RtlIpv6StringToAddressW
      2 ntoskrnl.exe.RtlLookupElementGenericTableAvl
      2 ntoskrnl.exe.RtlSecondsSince1980ToTime
      2 ntoskrnl.exe.RtlSetAllBits
      2 ntoskrnl.exe.RtlUnicodeToCustomCPN
      2 ntoskrnl.exe.RtlUpcaseUnicodeStringToCountedOemString
      2 ntoskrnl.exe.RtlUpperString
      2 ntoskrnl.exe.RtlWalkFrameChain
      2 ntoskrnl.exe.RtlxUnicodeStringToAnsiSize
      2 ntoskrnl.exe.SeDeleteAccessState
      2 ntoskrnl.exe.SeFilterToken
      2 ntoskrnl.exe.SeTokenIsAdmin
      2 ntoskrnl.exe.ZwCreateSymbolicLinkObject
      2 ntoskrnl.exe.ZwNotifyChangeKey
      2 ntoskrnl.exe.ZwQueryDirectoryObject
      2 ntoskrnl.exe.ZwSetEvent
      2 ntoskrnl.exe.ZwSetInformationObject
      2 ntoskrnl.exe.ZwSetTimer
      2 ntoskrnl.exe.ZwSetVolumeInformationFile
      2 ntoskrnl.exe._itoa
      2 ntoskrnl.exe._wcslwr
      2 ntoskrnl.exe.islower
      2 ntoskrnl.exe.srand
      2 ntoskrnl.exe.strcat
      2 ntoskrnl.exe.strncat
########################################################################

      1 ntoskrnl.exe.CcFastMdlReadWait
      1 ntoskrnl.exe.CcGetDirtyPages
      1 ntoskrnl.exe.CcRemapBcb
      1 ntoskrnl.exe.CcSetBcbOwnerPointer
      1 ntoskrnl.exe.CcSetLogHandleForFile
      1 ntoskrnl.exe.CcUnpinDataForThread
      1 ntoskrnl.exe.CmRegisterCallback
      1 ntoskrnl.exe.CmUnRegisterCallback
      1 ntoskrnl.exe.ExAllocatePoolWithQuota
      1 ntoskrnl.exe.ExDesktopObjectType
      1 ntoskrnl.exe.ExGetCurrentProcessorCounts
      1 ntoskrnl.exe.ExGetCurrentProcessorCpuUsage
      1 ntoskrnl.exe.ExInterlockedCompareExchange64
      1 ntoskrnl.exe.ExInterlockedInsertHeadList
      1 ntoskrnl.exe.ExReinitializeResourceLite
      1 ntoskrnl.exe.ExSemaphoreObjectType
      1 ntoskrnl.exe.ExWindowStationObjectType
      1 ntoskrnl.exe.ExfAcquirePushLockExclusive
      1 ntoskrnl.exe.ExfAcquirePushLockShared
      1 ntoskrnl.exe.ExfReleasePushLock
      1 ntoskrnl.exe.Exfi386InterlockedDecrementLong
      1 ntoskrnl.exe.FsRtlAddMcbEntry
      1 ntoskrnl.exe.FsRtlIncrementCcFastReadNoWait
      1 ntoskrnl.exe.FsRtlIncrementCcFastReadNotPossible
      1 ntoskrnl.exe.FsRtlIncrementCcFastReadResourceMiss
      1 ntoskrnl.exe.FsRtlIncrementCcFastReadWait
      1 ntoskrnl.exe.FsRtlInitializeMcb
      1 ntoskrnl.exe.FsRtlInsertPerFileObjectContext
      1 ntoskrnl.exe.FsRtlInsertPerStreamContext
      1 ntoskrnl.exe.FsRtlIsDbcsInExpression
      1 ntoskrnl.exe.FsRtlIsHpfsDbcsLegal
      1 ntoskrnl.exe.FsRtlIsPagingFile
      1 ntoskrnl.exe.FsRtlLookupLastLargeMcbEntry
      1 ntoskrnl.exe.FsRtlLookupLastMcbEntry
      1 ntoskrnl.exe.FsRtlLookupPerFileObjectContext
      1 ntoskrnl.exe.FsRtlLookupPerStreamContextInternal
      1 ntoskrnl.exe.FsRtlMdlRead
      1 ntoskrnl.exe.FsRtlMdlReadComplete
      1 ntoskrnl.exe.FsRtlNotifyFilterReportChange
      1 ntoskrnl.exe.FsRtlRemoveMcbEntry
      1 ntoskrnl.exe.FsRtlRemovePerFileObjectContext
      1 ntoskrnl.exe.FsRtlRemovePerStreamContext
      1 ntoskrnl.exe.FsRtlSplitLargeMcb
      1 ntoskrnl.exe.FsRtlUninitializeMcb
      1 ntoskrnl.exe.HalPrivateDispatchTable
      1 ntoskrnl.exe.InbvCheckDisplayOwnership
      1 ntoskrnl.exe.InbvDisplayString
      1 ntoskrnl.exe.InbvEnableBootDriver
      1 ntoskrnl.exe.InbvNotifyDisplayOwnershipLost
      1 ntoskrnl.exe.IoAdapterObjectType
      1 ntoskrnl.exe.IoAssignDriveLetters
      1 ntoskrnl.exe.IoAttachDeviceByPointer
      1 ntoskrnl.exe.IoAttachDeviceToDeviceStackSafe
      1 ntoskrnl.exe.IoCheckDesiredAccess
      1 ntoskrnl.exe.IoCheckFunctionAccess
      1 ntoskrnl.exe.IoCheckQuerySetFileInformation
      1 ntoskrnl.exe.IoCheckQuerySetVolumeInformation
      1 ntoskrnl.exe.IoCheckQuotaBufferValidity
      1 ntoskrnl.exe.IoCreateDisk
      1 ntoskrnl.exe.IoCreateStreamFileObjectLite
      1 ntoskrnl.exe.IoCsqRemoveNextIrp
      1 ntoskrnl.exe.IoEnqueueIrp
      1 ntoskrnl.exe.IoFastQueryNetworkAttributes
      1 ntoskrnl.exe.IoForwardIrpSynchronously
      1 ntoskrnl.exe.IoGetDeviceInterfaceAlias
      1 ntoskrnl.exe.IoGetRequestorProcessId
      1 ntoskrnl.exe.IoPageRead
      1 ntoskrnl.exe.IoQueryFileDosDeviceName
      1 ntoskrnl.exe.IoQueryFileInformation
      1 ntoskrnl.exe.IoReadDiskSignature
      1 ntoskrnl.exe.IoReadOperationCount
      1 ntoskrnl.exe.IoReadPartitionTable
      1 ntoskrnl.exe.IoReadTransferCount
      1 ntoskrnl.exe.IoSetFileOrigin
      1 ntoskrnl.exe.IoSetPartitionInformation
      1 ntoskrnl.exe.IoSetPartitionInformationEx
      1 ntoskrnl.exe.IoStatisticsLock
      1 ntoskrnl.exe.IoSynchronousPageWrite
      1 ntoskrnl.exe.IoVerifyPartitionTable
      1 ntoskrnl.exe.IoWMISetNotificationCallback
      1 ntoskrnl.exe.IoWriteOperationCount
      1 ntoskrnl.exe.IoWriteTransferCount
      1 ntoskrnl.exe.KdPowerTransition
      1 ntoskrnl.exe.Ke386CallBios
      1 ntoskrnl.exe.Ke386IoSetAccessProcess
      1 ntoskrnl.exe.Ke386QueryIoAccessMap
      1 ntoskrnl.exe.Ke386SetIoAccessMap
      1 ntoskrnl.exe.KeAcquireInStackQueuedSpinLockAtDpcLevel
      1 ntoskrnl.exe.KeAreApcsDisabled
      1 ntoskrnl.exe.KeCapturePersistentThreadState
      1 ntoskrnl.exe.KeGetPreviousMode
      1 ntoskrnl.exe.KeInitializeDeviceQueue
      1 ntoskrnl.exe.KeInitializeMutant
      1 ntoskrnl.exe.KeInsertDeviceQueue
      1 ntoskrnl.exe.KeInsertHeadQueue
      1 ntoskrnl.exe.KeIsAttachedProcess
      1 ntoskrnl.exe.KePulseEvent
      1 ntoskrnl.exe.KeQueryRuntimeThread
      1 ntoskrnl.exe.KeReadStateQueue
      1 ntoskrnl.exe.KeReleaseInStackQueuedSpinLockFromDpcLevel
      1 ntoskrnl.exe.KeReleaseMutant
      1 ntoskrnl.exe.KeRemoveByKeyDeviceQueue
      1 ntoskrnl.exe.KeRemoveByKeyDeviceQueueIfBusy
      1 ntoskrnl.exe.KeRemoveEntryDeviceQueue
      1 ntoskrnl.exe.KeSetEventBoostPriority
      1 ntoskrnl.exe.KeSetIdealProcessorThread
      1 ntoskrnl.exe.KeSetKernelStackSwapEnable
      1 ntoskrnl.exe.KeUpdateSystemTime
      1 ntoskrnl.exe.KeUserModeCallback
      1 ntoskrnl.exe.KiBugCheckData
      1 ntoskrnl.exe.LpcPortObjectType
      1 ntoskrnl.exe.LpcRequestWaitReplyPort
      1 ntoskrnl.exe.MmAdvanceMdl
      1 ntoskrnl.exe.MmGetVirtualForPhysical
      1 ntoskrnl.exe.MmMapMemoryDumpMdl
      1 ntoskrnl.exe.MmMapUserAddressesToPage
      1 ntoskrnl.exe.MmMapVideoDisplay
      1 ntoskrnl.exe.MmMapViewInSystemSpace
      1 ntoskrnl.exe.MmPrefetchPages
      1 ntoskrnl.exe.MmProtectMdlSystemAddress
      1 ntoskrnl.exe.MmSetAddressRangeModified
      1 ntoskrnl.exe.MmSetBankedSection
      1 ntoskrnl.exe.MmUnmapVideoDisplay
      1 ntoskrnl.exe.MmUnmapViewInSystemSpace
      1 ntoskrnl.exe.NlsLeadByteInfo
      1 ntoskrnl.exe.NtAdjustPrivilegesToken
      1 ntoskrnl.exe.NtAllocateVirtualMemory
      1 ntoskrnl.exe.NtConnectPort
      1 ntoskrnl.exe.NtCreateSection
      1 ntoskrnl.exe.NtDeleteFile
      1 ntoskrnl.exe.NtDuplicateObject #
      1 ntoskrnl.exe.NtFreeVirtualMemory
      1 ntoskrnl.exe.NtFsControlFile
      1 ntoskrnl.exe.NtLockFile
      1 ntoskrnl.exe.NtNotifyChangeDirectoryFile
      1 ntoskrnl.exe.NtQueryDirectoryFile
      1 ntoskrnl.exe.NtQueryEaFile
      1 ntoskrnl.exe.NtQueryQuotaInformationFile
      1 ntoskrnl.exe.NtQuerySecurityObject
      1 ntoskrnl.exe.NtRequestWaitReplyPort
      1 ntoskrnl.exe.NtSetQuotaInformationFile
      1 ntoskrnl.exe.NtSetVolumeInformationFile
      1 ntoskrnl.exe.NtUnlockFile
      1 ntoskrnl.exe.ObCreateObjectType
      1 ntoskrnl.exe.ObFindHandleForObject
      1 ntoskrnl.exe.ObIsDosDeviceLocallyMapped
      1 ntoskrnl.exe.ObQueryObjectAuditingByHandle
      1 ntoskrnl.exe.PoQueueShutdownWorkItem
      1 ntoskrnl.exe.PoShutdownBugCheck
      1 ntoskrnl.exe.PsChargeProcessPagedPoolQuota
      1 ntoskrnl.exe.PsDisableImpersonation
      1 ntoskrnl.exe.PsGetContextThread
      1 ntoskrnl.exe.PsGetProcessCreateTimeQuadPart
      1 ntoskrnl.exe.PsGetProcessExitTime
      1 ntoskrnl.exe.PsGetProcessSectionBaseAddress
      1 ntoskrnl.exe.PsGetProcessSecurityPort
      1 ntoskrnl.exe.PsLookupThreadByThreadId
      1 ntoskrnl.exe.PsReferencePrimaryToken
      1 ntoskrnl.exe.PsRestoreImpersonation
      1 ntoskrnl.exe.PsReturnProcessPagedPoolQuota
      1 ntoskrnl.exe.PsSetCreateThreadNotifyRoutine
      1 ntoskrnl.exe.PsSetProcessSecurityPort
      1 ntoskrnl.exe.RtlAnsiCharToUnicodeChar
      1 ntoskrnl.exe.RtlAssert
      1 ntoskrnl.exe.RtlCharToInteger
      1 ntoskrnl.exe.RtlCompareMemoryUlong
      1 ntoskrnl.exe.RtlCompressChunks
      1 ntoskrnl.exe.RtlConvertLongToLargeInteger
      1 ntoskrnl.exe.RtlConvertSidToUnicodeString
      1 ntoskrnl.exe.RtlCopyLuid
      1 ntoskrnl.exe.RtlCopyString
      1 ntoskrnl.exe.RtlDecompressBuffer
      1 ntoskrnl.exe.RtlDecompressChunks
      1 ntoskrnl.exe.RtlDeleteNoSplay
      1 ntoskrnl.exe.RtlDowncaseUnicodeString
      1 ntoskrnl.exe.RtlEnumerateGenericTableWithoutSplayingAvl
      1 ntoskrnl.exe.RtlFillMemoryUlong
      1 ntoskrnl.exe.RtlFindFirstRunClear
      1 ntoskrnl.exe.RtlFindLastBackwardRunClear
      1 ntoskrnl.exe.RtlFindLeastSignificantBit
      1 ntoskrnl.exe.RtlFindSetBits
      1 ntoskrnl.exe.RtlGetElementGenericTable
      1 ntoskrnl.exe.RtlGetSetBootStatusData
      1 ntoskrnl.exe.RtlInt64ToUnicodeString
      1 ntoskrnl.exe.RtlInvertRangeList
      1 ntoskrnl.exe.RtlIpv4AddressToStringExW
      1 ntoskrnl.exe.RtlIpv4AddressToStringW
      1 ntoskrnl.exe.RtlIpv4StringToAddressA
      1 ntoskrnl.exe.RtlIpv6AddressToStringA
      1 ntoskrnl.exe.RtlIpv6AddressToStringW
      1 ntoskrnl.exe.RtlIpv6StringToAddressA
      1 ntoskrnl.exe.RtlIsGenericTableEmpty
      1 ntoskrnl.exe.RtlIsRangeAvailable
      1 ntoskrnl.exe.RtlLargeIntegerDivide
      1 ntoskrnl.exe.RtlMapSecurityErrorToNtStatus
      1 ntoskrnl.exe.RtlPrefetchMemoryNonTemporal # 提示 一个buff 可能 mv到 cpu的cache 里面去.
      1 ntoskrnl.exe.RtlSetSaclSecurityDescriptor
      1 ntoskrnl.exe.RtlTimeToSecondsSince1980
      1 ntoskrnl.exe.RtlUnlockBootStatusData
      1 ntoskrnl.exe.RtlUpperChar
      1 ntoskrnl.exe.SeAuditHardLinkCreation
      1 ntoskrnl.exe.SeAuditingFileEventsWithContext
      1 ntoskrnl.exe.SeAuditingHardLinkEventsWithContext
      1 ntoskrnl.exe.SeCreateClientSecurityFromSubjectContext
      1 ntoskrnl.exe.SeDeleteObjectAuditAlarm
      1 ntoskrnl.exe.SeImpersonateClient
      1 ntoskrnl.exe.SeOpenObjectForDeleteAuditAlarm
      1 ntoskrnl.exe.SeRegisterLogonSessionTerminatedRoutine
      1 ntoskrnl.exe.SeReleaseSecurityDescriptor
      1 ntoskrnl.exe.SeTokenImpersonationLevel
      1 ntoskrnl.exe.SeUnregisterLogonSessionTerminatedRoutine
      1 ntoskrnl.exe.VfFailDeviceNode
      1 ntoskrnl.exe.VfFailSystemBIOS
      1 ntoskrnl.exe.VfIsVerificationEnabled
      1 ntoskrnl.exe.WmiGetClock
      1 ntoskrnl.exe.ZwAlertThread
      1 ntoskrnl.exe.ZwCancelTimer
      1 ntoskrnl.exe.ZwClearEvent
      1 ntoskrnl.exe.ZwConnectPort
      1 ntoskrnl.exe.ZwCreateTimer
      1 ntoskrnl.exe.ZwDisplayString
      1 ntoskrnl.exe.ZwFlushVirtualMemory
      1 ntoskrnl.exe.ZwLoadKey
      1 ntoskrnl.exe.ZwOpenProcessToken
      1 ntoskrnl.exe.ZwOpenThread
      1 ntoskrnl.exe.ZwQueryDefaultLocale
      1 ntoskrnl.exe.ZwQueryEaFile
      1 ntoskrnl.exe.ZwQueryFullAttributesFile
      1 ntoskrnl.exe.ZwQueryInformationThread
      1 ntoskrnl.exe.ZwReplaceKey
      1 ntoskrnl.exe.ZwResetEvent
      1 ntoskrnl.exe.ZwSaveKey
      1 ntoskrnl.exe.ZwSaveKeyEx
      1 ntoskrnl.exe.ZwSetEaFile
      1 ntoskrnl.exe.ZwSetInformationProcess
      1 ntoskrnl.exe.ZwSetSystemInformation
      1 ntoskrnl.exe.ZwUnloadKey
      1 ntoskrnl.exe.__chkstk
      1 ntoskrnl.exe._alloca_probe
      1 ntoskrnl.exe._strupr
      1 ntoskrnl.exe.atol
      1 ntoskrnl.exe.isprint
      1 ntoskrnl.exe.strcmp
      1 ntoskrnl.exe.towupper
      1 ntoskrnl.exe.vDbgPrintEx
      1 ntoskrnl.exe.wcscspn
      1 ntoskrnl.exe.wcstombs

