#!/usr/bin/perl
$pattern=shift;
foreach (<DATA>)
{
	
	if($_=~/$pattern/)
	{
		print ;
	}
}
__DATA__

#移动硬盘的一级目录
ie.pl sdb1:\_pre_cache
ie.pl sdb1:\_x_file
ie.pl sdb1:\all_chm
ie.pl sdb1:\dos_iso
ie.pl sdb1:\ebook
ie.pl sdb1:\game
ie.pl sdb1:\sf_mirror_iso
ie.pl sdb1:\soft_release
ie.pl sdb1:\teresa_iso
ie.pl sdb1:\win_sys_tools
ie.pl sdb2:\ghost_targz_iso
ie.pl sdb2:\kugou_mp3_iso
ie.pl sdb2:\linux_iso_windows
ie.pl sdb2:\linux_src_all_iso
ie.pl sdb2:\oss_site_all_iso
ie.pl sdb2:\Security
ie.pl sdb2:\vmware_disk_iso
ie.pl sdb3:\develop_IDE_ISO
ie.pl sdb3:\Green_software
ie.pl sdb3:\lindows
ie.pl sdb3:\office_03_07_10
ie.pl sdb3:\photo
ie.pl sdb3:\qimeng
ie.pl sdb3:\sf_mirror_all
ie.pl sdb3:\vc
ie.pl sdb3:\windows_pe_iso
ie.pl sdb4:\_daily_backup
ie.pl sdb4:\f13_srpm_download
ie.pl sdb4:\my_usb_video_driver
ie.pl sdb4:\sync
ie.pl sdb4:\teresa_thing
#移动硬盘的二级级目录, 以d_开头
ie.pl sdb1:\_x_file\d_frequent
ie.pl sdb1:\_x_file\d_qianlong_all_iso
ie.pl sdb2:\oss_site_all_iso\d_python_pypi_mirror_iso
#移动硬盘的所有的iso文件
ie.pl sdb1:\_x_file\_develop_20100711.iso
ie.pl sdb1:\_x_file\_develop_20110129.iso
ie.pl sdb1:\_x_file\_pre_cache.iso
ie.pl sdb1:\_x_file\_root__2009_07_03.iso
ie.pl sdb1:\_x_file\_root__2010_03_12.iso
ie.pl sdb1:\_x_file\_root__2010_07_01.iso
ie.pl sdb1:\_x_file\_root__2011_0205day.iso
ie.pl sdb1:\_x_file\_root__2011_0206day_.iso
ie.pl sdb1:\_x_file\_xfile_2010_09_10.iso
ie.pl sdb1:\_x_file\_xfile_2010_11.iso
ie.pl sdb1:\_x_file\_xfile_2010_12_2011_01.iso
ie.pl sdb1:\_x_file\_xfile_2010_1_4.iso
ie.pl sdb1:\_x_file\_xfile_2010_5_8.iso
ie.pl sdb1:\_x_file\_xfile_2011_02_mon_03_mon.iso
ie.pl sdb1:\_x_file\_xfile_2011_456_month.iso
ie.pl sdb1:\_x_file\_xfile_2011_78_month.iso
ie.pl sdb1:\_x_file\_xfile_2011_9_10_11_month.iso
ie.pl sdb1:\_x_file\_xfile_before_2009.iso
ie.pl sdb1:\_x_file\mfc_develop_2011_new.iso
ie.pl sdb1:\_x_file\mfc_develop_2011_new_all_cpp_src.iso
ie.pl sdb1:\all_chm\all_misc_cata.iso
ie.pl sdb1:\all_chm\chm_201106.iso
ie.pl sdb1:\all_chm\ftp.gnome.org.iso
ie.pl sdb1:\all_chm\gentoo.iso
ie.pl sdb1:\all_chm\linux_src_chm_0.iso
ie.pl sdb1:\all_chm\linux_src_chm_1.iso
ie.pl sdb1:\dos_iso\dos_0.iso
ie.pl sdb1:\ebook\嵌入式自学.iso
ie.pl sdb1:\ebook\实用黑客攻防高手捷径.iso
ie.pl sdb1:\ebook\数学.iso
ie.pl sdb1:\ebook\_book.iso
ie.pl sdb1:\ebook\ebook1.iso
ie.pl sdb1:\ebook\ebook10.iso
ie.pl sdb1:\ebook\ebook11.iso
ie.pl sdb1:\ebook\ebook2.iso
ie.pl sdb1:\ebook\ebook3.iso
ie.pl sdb1:\ebook\ebook4.iso
ie.pl sdb1:\ebook\ebook5.iso
ie.pl sdb1:\ebook\ebook6.iso
ie.pl sdb1:\ebook\ebook7.iso
ie.pl sdb1:\ebook\ebook8.iso
ie.pl sdb1:\ebook\ebook9.iso
ie.pl sdb1:\sf_mirror_iso\sf_a1.iso
ie.pl sdb1:\sf_mirror_iso\sf_a2.iso
ie.pl sdb1:\sf_mirror_iso\sf_b.iso
ie.pl sdb1:\sf_mirror_iso\sf_c1.iso
ie.pl sdb1:\sf_mirror_iso\sf_c2.iso
ie.pl sdb1:\sf_mirror_iso\sf_d1.iso
ie.pl sdb1:\sf_mirror_iso\sf_d2.iso
ie.pl sdb1:\sf_mirror_iso\sf_e.iso
ie.pl sdb1:\sf_mirror_iso\sf_e1.iso
ie.pl sdb1:\sf_mirror_iso\sf_e2.iso
ie.pl sdb1:\sf_mirror_iso\sf_f_1.iso
ie.pl sdb1:\sf_mirror_iso\sf_f_2.iso
ie.pl sdb1:\sf_mirror_iso\sf_g1.iso
ie.pl sdb1:\sf_mirror_iso\sf_g2.iso
ie.pl sdb1:\sf_mirror_iso\sf_h.iso
ie.pl sdb1:\sf_mirror_iso\sf_i.iso
ie.pl sdb1:\sf_mirror_iso\sf_j1.iso
ie.pl sdb1:\sf_mirror_iso\sf_j2.iso
ie.pl sdb1:\sf_mirror_iso\sf_k.iso
ie.pl sdb1:\sf_mirror_iso\sf_l.iso
ie.pl sdb1:\sf_mirror_iso\sf_m1.iso
ie.pl sdb1:\sf_mirror_iso\sf_m2.iso
ie.pl sdb1:\sf_mirror_iso\sf_n.iso
ie.pl sdb1:\sf_mirror_iso\sf_o1.iso
ie.pl sdb1:\sf_mirror_iso\sf_o2.iso
ie.pl sdb1:\sf_mirror_iso\sf_p1.iso
ie.pl sdb1:\sf_mirror_iso\sf_p2.iso
ie.pl sdb1:\sf_mirror_iso\sf_p3.iso
ie.pl sdb1:\sf_mirror_iso\sf_q.iso
ie.pl sdb1:\sf_mirror_iso\sf_r.iso
ie.pl sdb1:\sf_mirror_iso\sf_s1.iso
ie.pl sdb1:\sf_mirror_iso\sf_s2.iso
ie.pl sdb1:\sf_mirror_iso\sf_s3.iso
ie.pl sdb1:\sf_mirror_iso\sf_t1.iso
ie.pl sdb1:\sf_mirror_iso\sf_t2.iso
ie.pl sdb1:\sf_mirror_iso\sf_uv.iso
ie.pl sdb1:\sf_mirror_iso\sf_w.iso
ie.pl sdb1:\sf_mirror_iso\sf_xyz.iso
ie.pl sdb1:\teresa_iso\teresa2010_1_6month.iso
ie.pl sdb2:\ghost_targz_iso\ghost_targz_0.iso
ie.pl sdb2:\kugou_mp3_iso\KuGou_0.iso
ie.pl sdb2:\linux_iso_windows\电脑公司无插件版_v7.5_quick8.cn提供_.iso
ie.pl sdb2:\linux_iso_windows\[黑客之道：漏洞发掘的艺术]._随书光盘_.iso
ie.pl sdb2:\linux_iso_windows\as4.8_i386.iso
ie.pl sdb2:\linux_iso_windows\clonezilla-live-1.2.5-17-amd64.iso
ie.pl sdb2:\linux_iso_windows\cn_win2000_pro_with_sp4.iso
ie.pl sdb2:\linux_iso_windows\f13_i386.iso
ie.pl sdb2:\linux_iso_windows\f13_x86_64.iso
ie.pl sdb2:\linux_iso_windows\f8_i386.iso
ie.pl sdb2:\linux_iso_windows\Fedora-15-i686-Live-Desktop.iso
ie.pl sdb2:\linux_iso_windows\fedora13_livecd-20100721.iso
ie.pl sdb2:\linux_iso_windows\fulldisk-r5.5-with-log-0730.iso
ie.pl sdb2:\linux_iso_windows\GHOSTXP_SP3电脑公司特别版_10.8.iso
ie.pl sdb2:\linux_iso_windows\GHOSTXP_SP3_2011_DNGSxz03.iso
ie.pl sdb2:\linux_iso_windows\gpxe.iso
ie.pl sdb2:\linux_iso_windows\grub.iso
ie.pl sdb2:\linux_iso_windows\livecd-fedora_v2-20100730.iso
ie.pl sdb2:\linux_iso_windows\livecd_f13_x86_64_20100830.iso
ie.pl sdb2:\linux_iso_windows\livecd_f13_x86_i686_20100830.iso
ie.pl sdb2:\linux_iso_windows\qianlong_2.3.8_no_mksystem.iso
ie.pl sdb2:\linux_iso_windows\qzj_mdf_黑客之道：漏洞发掘的艺术._随书光盘_.iso
ie.pl sdb2:\linux_iso_windows\rhel-server-6.0-i386-dvd.iso
ie.pl sdb2:\linux_iso_windows\rhel-server-6.0-x86_64-dvd.iso
ie.pl sdb2:\linux_src_all_iso\all_cata.iso
ie.pl sdb2:\linux_src_all_iso\Embedded_iso.iso
ie.pl sdb2:\linux_src_all_iso\linux_src_2007_10.iso
ie.pl sdb2:\linux_src_all_iso\linux_src_2008_10_11_12.iso
ie.pl sdb2:\linux_src_all_iso\linux_src_before_2009.iso
ie.pl sdb2:\linux_src_all_iso\src_2009.iso
ie.pl sdb2:\oss_site_all_iso\_oss_site_all_1.iso
ie.pl sdb2:\oss_site_all_iso\oss_site_all_2.iso
ie.pl sdb2:\Security\Backtrack_v1.iso
ie.pl sdb2:\Security\BT4.iso
ie.pl sdb2:\Security\security1_expand_all.iso
ie.pl sdb2:\Security\security_iso1.iso
ie.pl sdb2:\Security\sf_security.iso
ie.pl sdb2:\vmware_disk_iso\vmware_disk_0.iso
ie.pl sdb2:\vmware_disk_iso\vmware_disk_1.iso
ie.pl sdb3:\develop_IDE_ISO\develop_IDE.iso
ie.pl sdb3:\develop_IDE_ISO\develop_IDE2.iso
ie.pl sdb3:\develop_IDE_ISO\Win7_SDK_EN_DVD.iso
ie.pl sdb3:\lindows\gnuwinII_bonus_November_30_2004_1_.iso
ie.pl sdb3:\lindows\gnuwinII_November_30_2004.iso
ie.pl sdb3:\lindows\lindows_0.iso
ie.pl sdb3:\lindows\lindows_2.iso
ie.pl sdb3:\lindows\src_exe_mfc_dsp_ISO1.iso
ie.pl sdb3:\lindows\src_exe_mfc_dsp_ISO2.iso
ie.pl sdb3:\lindows\ttcs_osswin_cd_v1.99e.iso
ie.pl sdb3:\lindows\winik6CD1.iso
ie.pl sdb3:\lindows\winik6CD2.iso
ie.pl sdb3:\office_03_07_10\office_03_07_10.iso
ie.pl sdb3:\photo\宝宝图片总目录0.iso
ie.pl sdb3:\photo\宝宝图片总目录2_2010.iso
ie.pl sdb3:\photo\宝宝图片总目录3_2011_56789.iso
ie.pl sdb3:\photo\宝宝图片总目录_3_2011_04.iso
ie.pl sdb3:\photo\其他人.iso
ie.pl sdb3:\photo\钱温图片总目录.iso
ie.pl sdb3:\photo\小芳4月北京.iso
ie.pl sdb3:\photo\2011_06_photo_温州.iso
ie.pl sdb3:\photo\xiaoxiao_photo.iso
ie.pl sdb3:\qimeng\qimeng1_iso.iso
ie.pl sdb3:\qimeng\qimeng2_iso.iso
ie.pl sdb3:\qimeng\qimeng3_iso.iso
ie.pl sdb3:\windows_pe_iso\windows_pe_iso.iso
ie.pl sdb4:\my_usb_video_driver\dongfan_dianzhi_export.iso
ie.pl sdb4:\my_usb_video_driver\jingrong_ehome.iso
