#!/usr/bin/perl

my $file=shift or die("Usage: $0 input_file \n");
for(<DATA>)
{
	chomp;
	print "\n";
	print "openssl enc $_ 		-in $file 		-out $file.$_ \n";
	print "openssl enc $_ -d 	-in $file.$_    -out $file  \n"

}
__DATA__
-aes-128-cfb               
-aes-128-ctr               
-aes-128-ofb               
-aes-192-cfb               
-aes-192-ctr               
-aes-192-ofb               
-aes-256-cfb1              
-aes-256-ecb               
-aes-256-xts               
-aes256                    
-bf-cfb                    
-blowfish                  
-camellia-128-cfb1         
-camellia-128-ofb          
-camellia-192-cfb1         
-camellia-192-ofb          
-camellia-256-cfb1         
-camellia-256-ofb          
-camellia256               
-cast5-cbc                 
-cast5-ofb                 
-des-cfb                   
-des-ecb                   
-des-ede-cfb               
-des-ede3-cbc              
-des-ede3-cfb8             
-des3                      
-id-aes128-GCM             
-idea                      
-idea-ecb                  
-rc2-40-cbc                
-rc2-cfb                   
-rc4                       
-seed                      
-seed-ecb                  
-aes-128-cbc              
-aes-128-cfb1             
-aes-128-cfb8             
-aes-128-ecb              
-aes-128-gcm              
-aes-128-xts              
-aes-192-cbc              
-aes-192-cfb1             
-aes-192-cfb8             
-aes-192-ecb              
-aes-192-gcm              
-aes-256-cbc              
-aes-256-cfb              
-aes-256-cfb8             
-aes-256-ctr              
-aes-256-gcm              
-aes-256-ofb              
-aes128                   
-aes192                   
-bf                       
-bf-cbc                   
-bf-ecb                   
-bf-ofb                   
-camellia-128-cbc         
-camellia-128-cfb         
-camellia-128-cfb8        
-camellia-128-ecb         
-camellia-192-cbc         
-camellia-192-cfb         
-camellia-192-cfb8        
-camellia-192-ecb         
-camellia-256-cbc         
-camellia-256-cfb         
-camellia-256-cfb8        
-camellia-256-ecb         
-camellia128              
-camellia192              
-cast                     
-cast-cbc                 
-cast5-cfb                
-cast5-ecb                
-des                      
-des-cbc                  
-des-cfb1                 
-des-cfb8                 
-des-ede                  
-des-ede-cbc              
-des-ede-ofb              
-des-ede3                 
-des-ede3-cfb             
-des-ede3-cfb1            
-des-ede3-ofb             
-des-ofb                  
-desx                     
-desx-cbc                 
-id-aes192-GCM            
-id-aes256-GCM            
-idea-cbc                 
-idea-cfb                 
-idea-ofb                 
-rc2                      
-rc2-64-cbc               
-rc2-cbc                  
-rc2-ecb                  
-rc2-ofb                  
-rc4-40                   
-rc4-hmac-md5             
-seed-cbc                 
-seed-cfb                 
-seed-ofb                 
