#!/usr/bin/perl 
#use strict;
#use warnings;
#G:\sdb2\linux_src_iso
#Security_iso
#注意: 这里不要引号.
# J:\sdb2\linux_iso_windows
# cygwin 环境下面:  
#	find -type d   |sed 's/^./sdb1:/g'  |sed 's/\//\\\\/g'
#	find -type d   |sed 's/^./sdb1:/g'  |sed 's/\//\\\\/g' |sed 's/$/\\\\/g'  |sort
#   find -type d   |sed 's/^./sdb1:\/sdb2\/linux_iso_windows/g'  |sed 's/\//\\\\/g' |sed 's/$/\\\\/g'  |sort

#用绝对路径的方式 
#find  /cygdrive/j/sdb2  -type d  |sed 's|/cygdrive/j/|sdb1:/|g' |sed 's/\//\\\\/g' |sed 's/$/\\\\/g'  |sort
@g_iso_paths= qw(

sdb1:\\sdb2\\
sdb1:\\sdb2\\Security_iso\\
sdb1:\\sdb2\\Security_iso\\ophcrack-tables\\
sdb1:\\sdb2\\Security_iso\\ophcrack-tables\\rainbow_spical_winxp\\
sdb1:\\sdb2\\Security_iso\\ophcrack-tables\\tables_vista_free\\
sdb1:\\sdb2\\Security_iso\\ophcrack-tables\\tables_vista_spical_NTHASH\\
sdb1:\\sdb2\\Security_iso\\ophcrack-tables\\tables_xp_free_fast\\
sdb1:\\sdb2\\Security_iso\\ophcrack-tables\\tables_xp_free_small\\
sdb1:\\sdb2\\Security_iso\\security_iso2\\
sdb1:\\sdb2\\ghost_targz_iso\\
sdb1:\\sdb2\\linux_iso_windows\\
sdb1:\\sdb2\\linux_iso_windows\\Windows7_win2008\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2000\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2000\\msdn_ISO_sp0\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2000\\msdn_ISO_sp0\\WIN2000_PRO_DEDUG\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2000\\msdn_ISO_sp0\\WIN2000_PRO_SERVER_ADVSERVER\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\32bit\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\32bit\\DISC1\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\32bit\\DISC2\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\64bit\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\64bit\\DISC1\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\Win2003_R2\\64bit\\DISC2\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\msdn_ISO_sp0\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\msdn_ISO_sp0\\WIN2003_ENT_DEBUG\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\msdn_ISO_sp0\\WIN2003_STANDARD_ENTERPRISE\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\msdn_ISO_sp0\\WIN2003_WEB\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_2003\\windows_2003_sp2_language_pack\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_8\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_Server_2012\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_xp\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_xp\\msdn_ISO_sp0\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_xp\\msdn_ISO_sp0\\WINXPSP1_TABLET\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_xp\\msdn_ISO_sp0\\WINXPSP1_TABLET_DEBUG\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_xp\\msdn_ISO_sp0\\WINXP_HOME_PRO\\
sdb1:\\sdb2\\linux_iso_windows\\Windows_xp\\msdn_ISO_sp0\\WINXP_PRO_DEBUG\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.4-i386-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.4-x86_64-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.5-i386-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.5-x86_64-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.6-x86_64-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.8-i386-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\CentOS-4.8-x86_64-binDVD\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\bt\\
sdb1:\\sdb2\\linux_iso_windows\\centos4\\centos_4_0\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_0\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_1\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_2\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_3\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_4\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_5\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_6\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_7\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_8\\
sdb1:\\sdb2\\linux_iso_windows\\centos5\\centos_5_9\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\centos_6_0\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\centos_6_1\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\centos_6_2\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\centos_6_3\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\centos_6_4\\
sdb1:\\sdb2\\linux_iso_windows\\centos6\\centos_6_5\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\centos_2_1\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\centos_3_1\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\centos_3_4\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\centos_3_5\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\centos_3_7\\
sdb1:\\sdb2\\linux_iso_windows\\centos_\\centos_3_9\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\debian_2_0\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\debian_2_1\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\debian_3_0\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\debian_4_0\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\debian_5_0\\
sdb1:\\sdb2\\linux_iso_windows\\debian\\debian_6_0\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\FC_1\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\autoinst\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\f17\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\f17\\Fedora-17-x86_64-DVD\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fc_5\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_10\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_11\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_13\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_14\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_16\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_18\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_8\\
sdb1:\\sdb2\\linux_iso_windows\\fedora_all\\fedora_9\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\RedHat_7.1\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_6.2\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_6.2\\doc\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_7.0\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_7.2\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_7_3\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_8\\
sdb1:\\sdb2\\linux_iso_windows\\redhat_old_6_7_8_9\\redhat_9\\
sdb1:\\sdb2\\linux_iso_windows\\rhel3_redhat_as3\\
sdb1:\\sdb2\\linux_iso_windows\\rhel3_redhat_as3\\rhel_3_5\\
sdb1:\\sdb2\\linux_iso_windows\\rhel3_redhat_as3\\rhel_3_9\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\misc\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\rhel_4_0\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\rhel_4_4\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\rhel_4_6\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\rhel_4_7\\
sdb1:\\sdb2\\linux_iso_windows\\rhel4_redhat_as4\\rhel_4_8\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\misc_vt\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5.0\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_10\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_1\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_2\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_3\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_4\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_5\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_6\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_7\\
sdb1:\\sdb2\\linux_iso_windows\\rhel5_redhat_as5\\rhel_5_8\\
sdb1:\\sdb2\\linux_iso_windows\\rhel6_redhat_as6\\
sdb1:\\sdb2\\linux_iso_windows\\rhel6_redhat_as6\\rhel_6_0\\
sdb1:\\sdb2\\linux_iso_windows\\rhel6_redhat_as6\\rhel_6_1\\
sdb1:\\sdb2\\linux_iso_windows\\rhel6_redhat_as6\\rhel_6_2\\
sdb1:\\sdb2\\linux_iso_windows\\rhel6_redhat_as6\\rhel_6_3\\
sdb1:\\sdb2\\linux_iso_windows\\rhel6_redhat_as6\\rhel_6_4\\
sdb1:\\sdb2\\linux_iso_windows\\rhel7_redhat_as7\\
sdb1:\\sdb2\\linux_iso_windows\\win98\\
sdb1:\\sdb2\\linux_iso_windows\\windows_vista\\
sdb1:\\sdb2\\linux_iso_windows__autoinst\\
sdb1:\\sdb2\\linux_iso_windows__autoinst\\new\\
sdb1:\\sdb2\\linux_iso_windows_business\\
sdb1:\\sdb2\\linux_iso_windows_ext\\
sdb1:\\sdb2\\linux_iso_windows_ext\\HP\\
sdb1:\\sdb2\\linux_iso_windows_ext\\HP\\DOC\\
sdb1:\\sdb2\\linux_iso_windows_ext\\HP\\HP-UNIX_Patch_Bundle_till_Sep.2011_\\
sdb1:\\sdb2\\linux_iso_windows_ext\\HP\\HP-UX_11i_v3\\
sdb1:\\sdb2\\linux_iso_windows_ext\\HP\\depot\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_AIX_mksysb_iso\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\AIX5300-09\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\AIX_6.1\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\AIX_7.1_TL_7100-00-01\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\HMC_V7R740\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\HMC_V7R740\\VMware_Workstation_Rom\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\PowerVM-Virtual-IO-Server-v2.2.0.12-fp24-sp2\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\PowerVM_2.2.1\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_aix_vios_os_iso\\aix5300-11\\
sdb1:\\sdb2\\linux_iso_windows_ext\\IBM_linux_ppc_iso\\
sdb1:\\sdb2\\linux_iso_windows_ext\\Solaries\\
sdb1:\\sdb2\\linux_iso_windows_ext\\android\\
sdb1:\\sdb2\\linux_iso_windows_ext\\apple_mac\\
sdb1:\\sdb2\\linux_iso_windows_ext\\apple_mac_hack\\
sdb1:\\sdb2\\linux_iso_windows_ext\\boot_ldr\\
sdb1:\\sdb2\\linux_iso_windows_ext\\bsd_freebsd\\
sdb1:\\sdb2\\linux_iso_windows_ext\\bsd_freebsd\\FreeBSD-9.0-RELEASE-i386-all\\
sdb1:\\sdb2\\linux_iso_windows_ext\\bsd_netbsd\\
sdb1:\\sdb2\\linux_iso_windows_ext\\bsd_openbsd\\
sdb1:\\sdb2\\linux_iso_windows_ext\\bt\\
sdb1:\\sdb2\\linux_iso_windows_ext\\dos_freedos\\
sdb1:\\sdb2\\linux_iso_windows_ext\\floppy_img\\
sdb1:\\sdb2\\linux_iso_windows_ext\\gentoo_\\
sdb1:\\sdb2\\linux_iso_windows_ext\\lfs\\
sdb1:\\sdb2\\linux_iso_windows_ext\\minix\\
sdb1:\\sdb2\\linux_iso_windows_ext\\netware\\
sdb1:\\sdb2\\linux_iso_windows_ext\\ovd_iso\\
sdb1:\\sdb2\\linux_iso_windows_ext\\pfsense\\
sdb1:\\sdb2\\linux_iso_windows_ext\\reactos_\\
sdb1:\\sdb2\\linux_iso_windows_ext\\sco\\
sdb1:\\sdb2\\linux_iso_windows_ext\\slackwave\\
sdb1:\\sdb2\\linux_iso_windows_ext\\suse\\
sdb1:\\sdb2\\linux_iso_windows_ext\\ubuntu\\
sdb1:\\sdb2\\linux_iso_windows_ext\\vmware_ESX_iso\\
sdb1:\\sdb2\\linux_iso_windows_ext\\xen_server\\
sdb1:\\sdb2\\linux_src_all_iso\\
sdb1:\\sdb2\\linux_src_rpm_iso\\
sdb1:\\sdb2\\vmware_disk_iso\\



);


