#!/bin/sh
[ ! $# -eq 1 ]&&echo "Usage: rpm_depends package"&& exit -4
TEMP=/tmp/temp
if [ -f $TEMP ];then
	cat /dev/null > $TEMP
fi
cat <<EOF >$TEMP
4Suite system_config_httpd 
alchemist system_config_httpd 
alchemist alchemist_devel 
alchemist system_config_printer 
alchemist system_config_printer 
alsa_lib alsa_lib_devel 
alsa_lib control_center 
alsa_lib pwlib 
alsa_lib system_config_soundcard 
alsa_lib_devel arts_devel 
alsa_lib_devel esound_devel 
alsa_lib_devel SDL_devel 
alsa_utils system_config_soundcard 
amanda amanda_devel 
amanda amanda_client 
amanda amanda_server 
anaconda_help anaconda 
apel_xemacs xemacs_sumo 
apr httpd 
apr apr_devel 
apr_devel httpd_devel 
apr_devel apr_util_devel 
apr_devel subversion_devel 
apr_util apr_util_devel 
apr_util_devel httpd_devel 
apr_util_devel subversion_devel 
arts arts_devel 
arts gstreamer_plugins 
arts kdeaddons 
arts kdelibs 
arts_devel kdelibs_devel 
aspell aspell_en 
aspell aspell_ca 
aspell aspell_cs 
aspell aspell_cy 
aspell aspell_da 
aspell aspell_de 
aspell aspell_devel 
aspell aspell_el 
aspell aspell_es 
aspell aspell_fr 
aspell aspell_it 
aspell aspell_nl 
aspell aspell_no 
aspell aspell_pl 
aspell aspell_pt 
aspell aspell_sv 
aspell squirrelmail 
aspell xfig 
aspell_devel gtkspell_devel 
aspell_en aspell 
atk atk_devel 
atk gail 
atk gtk2 
atk libgail_gnome 
atk_devel gok_devel 
atk_devel gtk2_devel 
at_spi gok 
at_spi at_spi_devel 
at_spi gnopernicus 
at_spi libgail_gnome 
audiofile arts 
audiofile audiofile_devel 
audiofile_devel arts_devel 
audiofile_devel esound_devel 
authconfig authconfig_gtk 
authconfig_gtk firstboot 
autoconf kdevelop 
autoconf automake17 
autoconf automake 
autoconf libtool 
automake kdevelop 
automake libtool 
basesystem glibc 
bash info 
bash sysklogd 
bash initscripts 
bash gpm 
bash sysreport 
bash sendmail 
bash vixie_cron 
bash ypbind 
bash inn 
bash mysql 
bash mysqlclient10 
bash pvm 
bash squid 
bash vnc_server 
bash ypserv 
beecrypt rpm 
beecrypt beecrypt_devel 
beecrypt beecrypt_python 
bind bind_chroot 
bind bind_devel 
bind caching_nameserver 
bind caching_nameserver 
bind_utils bind 
binutils elfutils 
binutils gcc 
binutils compat_gcc_32 
binutils gcc4 
binutils gcc4 
binutils oprofile 
bitmap_fonts vte 
bluez_libs bluez_libs 
bluez_libs bluez_hcidump 
bluez_libs bluez_libs_devel 
bluez_libs bluez_utils 
bluez_libs bluez_utils_cups 
bogl bogl_bterm 
bogl bogl_devel 
boost boost_devel 
booty anaconda 
bzip2 man 
bzip2 bzip2_devel 
bzip2 system_config_printer 
bzip2_devel ImageMagick_c++_devel 
bzip2_devel ImageMagick_devel 
bzip2_devel kdelibs_devel 
bzip2_libs bzip2 
bzip2_libs bzip2_devel 
Canna_libs Canna_devel 
cdda2wav xcdroast 
cdparanoia_libs cdparanoia 
cdparanoia_libs cdparanoia_devel 
cdparanoia_libs gstreamer_plugins 
cdparanoia_libs kdebase 
cdrecord cdrecord_devel 
cdrecord k3b 
cdrecord nautilus_cd_burner 
cdrecord xcdroast 
checkpolicy setools 
checkpolicy selinux_policy_targeted_sources 
chkconfig hotplug 
chkconfig dbus 
chkconfig hal 
chkconfig cyrus_sasl 
chkconfig kudzu 
chkconfig ntsysv 
chkconfig at 
chkconfig NetworkManager 
chkconfig openssh_server 
chkconfig pcmcia_cs 
chkconfig sendmail 
chkconfig freeradius 
chkconfig autofs 
chkconfig firstboot 
chkconfig FreeWnn 
chkconfig mysql 
chkconfig mysqlclient10 
chkconfig radvd 
chkconfig system_config_date 
chkfontpath urw_fonts 
compat_gcc_32 compat_gcc_32_c++ 
compat_glibc_headers compat_glibc 
compat_libstdc++_33 compat_gcc_32_c++ 
compat_libstdc++_33 openoffice.org 
comps_extras system_config_packages 
control_center gnome_session 
control_center gnome_volume_manager 
coreutils shadow_utils 
coreutils pam 
coreutils prelink 
coreutils minicom 
coreutils a2ps 
coreutils brltty 
coreutils katana_build 
cpio mkinitrd 
cpp gcc 
cracklib pam 
cracklib_dicts pam 
crontabs anacron 
crontabs webalizer 
cups desktop_printing 
cups bluez_utils_cups 
cups gimp_print_cups 
cups hal_cups_utils 
cups libgnomecups 
cups system_config_printer 
cups_devel libgnomecups_devel 
cups_libs cups 
cups_libs cups_devel 
cups_libs kdelibs 
cups_libs libgnomecups 
curl curl_devel 
cyrus_imapd cyrus_imapd_devel 
cyrus_imapd cyrus_imapd_murder 
cyrus_imapd cyrus_imapd_nntp 
cyrus_sasl cyrus_sasl_md5 
cyrus_sasl openldap 
cyrus_sasl cyrus_sasl_plain 
cyrus_sasl sendmail 
cyrus_sasl cyrus_sasl_devel 
cyrus_sasl cyrus_sasl_gssapi 
cyrus_sasl cyrus_sasl_ntlm 
cyrus_sasl cyrus_sasl_sql 
cyrus_sasl compat_openldap 
cyrus_sasl cyrus_imapd 
cyrus_sasl exim 
cyrus_sasl postfix 
cyrus_sasl_devel openldap_devel 
cyrus_sasl_md5 openldap 
db4 pam 
db4 pam_ccreds 
db4 db4_devel 
db4 db4_java 
db4 db4_tcl 
db4 db4_utils 
db4 libtabe 
db4 openoffice.org 
db4_devel apr_util_devel 
dbskkd_cdb skkinput 
dbus dbus_glib 
dbus hal 
dbus NetworkManager 
dbus cups 
dbus desktop_printing 
dbus gnome_volume_manager 
dbus dbus_devel 
dbus dbus_python 
dbus dbus_x11 
dbus NetworkManager_gnome 
dbus_devel hal_devel 
dbus_glib hal 
dbus_glib NetworkManager 
dbus_glib NetworkManager_gnome 
dbus_python hal_gnome 
dbus_python system_config_packages 
dbus_x11 desktop_printing 
desktop_backgrounds_basic kdebase 
desktop_backgrounds_basic kdelibs 
desktop_backgrounds_basic nautilus 
desktop_file_utils redhat_menus 
desktop_file_utils eog 
desktop_file_utils file_roller 
desktop_file_utils firefox 
desktop_file_utils gnome_utils 
desktop_file_utils bug_buddy 
desktop_file_utils eel2 
desktop_file_utils gimp 
desktop_file_utils gpdf 
desktop_file_utils gthumb 
desktop_file_utils HelixPlayer 
desktop_file_utils mozilla 
desktop_file_utils openoffice.org 
desktop_file_utils rhythmbox 
desktop_file_utils system_config_packages 
desktop_file_utils tetex 
desktop_file_utils tetex_xdvi 
desktop_file_utils thunderbird 
desktop_file_utils xmms 
devhelp devhelp_devel 
device_mapper lvm2 
dhclient NetworkManager 
dhcp dhcp_devel 
dialog tetex 
dialog tn5250 
diffutils man 
diffutils cyrus_imapd 
distcache distcache_devel 
docbook_dtds docbook_slides 
docbook_dtds docbook_simple 
docbook_dtds docbook_style_dsssl 
docbook_dtds docbook_utils 
docbook_dtds openjade 
docbook_dtds scrollkeeper 
docbook_dtds xmlto 
docbook_simple docbook_slides 
docbook_style_dsssl docbook_utils 
docbook_style_xsl gtk_doc 
docbook_utils docbook_utils_pdf 
docbook_utils gtk_doc 
dosfstools mkbootdisk 
doxygen doxygen_doxywizard 
e2fsprogs initscripts 
e2fsprogs mkinitrd 
e2fsprogs up2date 
e2fsprogs cyrus_imapd 
e2fsprogs e2fsprogs_devel 
e2fsprogs rhn_applet 
e2fsprogs_devel krb5_devel 
ecj java_1.4.2_gcj_compat_devel 
ed tetex 
eel2 eel2_devel 
eel2 gedit 
eel2 nautilus 
eel2 rhythmbox 
eel2_devel gedit_devel 
eject nautilus 
elfutils rpm_python 
elfutils elfutils_devel 
elfutils_libelf elfutils 
elfutils_libelf elfutils_libelf_devel 
elfutils_libelf_devel elfutils_devel 
elinks docbook_utils 
emacs_common emacs_nox 
emacs_common apel 
emacs_common emacs 
emacs_common ruby_mode 
eog nautilus 
esound esound_devel 
esound gnome_libs 
esound libgnomeui 
esound_devel gok_devel 
esound_devel arts_devel 
esound_devel gnome_libs_devel 
esound_devel libgnome_devel 
esound_devel libgnomeui_devel 
esound_devel libgnomeui_devel 
ethereal ethereal_gnome 
ethtool initscripts 
evolution evolution_connector 
evolution evolution_devel 
evolution_data_server evolution_data_server_devel 
evolution_data_server evolution 
evolution_data_server evolution_webcal 
evolution_data_server gnome_panel 
exim exim_sa 
expat expat_devel 
expat perl_XML_Parser 
expat_devel apr_util_devel 
expat_devel neon_devel 
expect dejagnu 
expect expect_devel 
expect expectk 
festival gnome_speech 
festival festival_devel 
file php 
file cyrus_imapd 
file rpm_build 
filesystem basesystem 
filesystem SysVinit 
filesystem mkinitrd 
filesystem lockdev 
filesystem xinetd 
filesystem nautilus 
findutils coreutils 
findutils mkinitrd 
findutils prelink 
findutils man 
findutils am_utils 
flac flac_devel 
flex kdevelop 
fontconfig bitmap_fonts 
fontconfig bitmap_fonts_cjk 
fontconfig fontconfig_devel 
fontconfig fonts_arabic 
fontconfig fonts_bengali 
fontconfig fonts_hebrew 
fontconfig fonts_xorg_base 
fontconfig fonts_xorg_syriac 
fontconfig fonts_xorg_truetype 
fontconfig gimp 
fontconfig libgnomeui 
fontconfig qt 
fontconfig ttfonts_ko 
fontconfig urw_fonts 
fontconfig_devel pango_devel 
fontconfig_devel xorg_x11_devel 
fonts_xorg_75dpi emacs 
foomatic Omni_foomatic 
foomatic system_config_printer 
freeglut freeglut_devel 
freeradius freeradius_mysql 
freeradius freeradius_postgresql 
freeradius freeradius_unixODBC 
freetype fontconfig 
freetype xorg_x11_libs 
freetype dia 
freetype freetype_demos 
freetype freetype_devel 
freetype freetype_utils 
freetype libgnomeprint22_devel 
freetype librsvg2 
freetype pango 
freetype pango 
freetype_devel fontconfig_devel 
freetype_devel ImageMagick_c++_devel 
freetype_devel ImageMagick_devel 
freetype_devel librsvg2_devel 
freetype_devel pango_devel 
FreeWnn_libs FreeWnn_devel 
fribidi fribidi_devel 
gail at_spi 
gail gail_devel 
gail gtkhtml2 
gail_devel eel2_devel 
gail_devel glade2 
gail_devel gok_devel 
gail_devel at_spi_devel 
gail_devel gtkhtml2_devel 
gamin gamin_devel 
gawk initscripts 
gawk prelink 
gawk sysreport 
gawk netdump 
gawk nfs_utils 
gawk sendmail 
gawk httpd 
gawk linuxdoc_tools 
gawk am_utils 
gawk autoconf213 
gawk autoconf 
gawk autofs 
gawk ypserv 
gcc gcc_c++ 
gcc gcc_gnat 
gcc gcc_objc 
gcc lam 
gcc gcc_g77 
gcc gcc_java 
gcc libtool 
gcc4 gcc4_c++ 
gcc4 gcc4_gfortran 
gcc4 libmudflap_devel 
gcc_c++ lam 
gcc_g77 lam 
gcc_java java_1.4.2_gcj_compat 
gcc_java katana_build 
GConf2 eog 
GConf2 file_roller 
GConf2 gedit 
GConf2 gnome_session 
GConf2 gnome_terminal 
GConf2 GConf2_devel 
GConf2 gconf_editor 
GConf2 ggv 
GConf2 gnome_desktop 
GConf2 gnome_games 
GConf2 gnomemeeting 
GConf2 gnome_netstatus 
GConf2 gnome_netstatus 
GConf2 gnome_panel 
GConf2 gnome_pilot 
GConf2 gnome_python2_gconf 
GConf2 gnome_vfs2 
GConf2 gstreamer_plugins 
GConf2 libgnome 
GConf2 libgnomeui 
GConf2 NetworkManager_gnome 
GConf2 sound_juicer 
GConf2 vino 
GConf2 vino 
GConf2 yelp 
GConf2_devel gnome_desktop_devel 
GConf2_devel gnome_vfs2_devel 
GConf2_devel libgnome_devel 
GConf2_devel libgnomeui_devel 
gd gd_devel 
gd libwmf 
gd gd_progs 
gd mrtg 
gdb kdbg 
gdb bug_buddy 
gdb pstack 
gdbm gdbm_devel 
gd_devel libwmf_devel 
gdk_pixbuf gdk_pixbuf_devel 
gdk_pixbuf gtk+ 
gettext gettext_devel 
gettext mutt 
ghostscript ghostscript_devel 
ghostscript ghostscript_fonts 
ghostscript ghostscript_gtk 
ghostscript hpijs 
ghostscript libgnomeprint22 
ghostscript system_config_printer 
ghostscript_fonts ghostscript 
ghostscript_fonts libgnomeprint22 
gimp gimp_data_extras 
gimp gimp_help 
gimp gimp_devel 
gimp gimp_gap 
gimp gimp_print_plugin 
gimp_print gimp 
gimp_print gimp_print_devel 
gimp_print gimp_print_plugin 
gimp_print gimp_print_utils 
glib glib_devel 
glib gtk+ 
glib2 pyxf86config 
glib2 pam 
glib2 authconfig 
glib2 hal 
glib2 diskdumputils 
glib2 NetworkManager 
glib2 dia 
glib2 gaim 
glib2 ghostscript 
glib2 gimp 
glib2 glib2_devel 
glib2 gstreamer 
glib2 gstreamer_plugins 
glib2 gtk2 
glib2 hal_cups_utils 
glib2 libcroco 
glib2 libcroco_devel 
glib2 libgcj 
glib2 libgnome 
glib2 libgnomeui 
glib2 libgsf 
glib2 libgtop2 
glib2 libsoup 
glib2 libwnck 
glib2 NetworkManager_gnome 
glib2 pango 
glib2 pyorbit 
glib2 shared_mime_info 
glib2 sound_juicer 
glib2_devel libbonoboui_devel 
glib2_devel gnome_desktop_devel 
glib2_devel libgtop2_devel 
glib2_devel arts_devel 
glib2_devel atk_devel 
glib2_devel dbus_devel 
glib2_devel GConf2_devel 
glib2_devel gnome_keyring_devel 
glib2_devel gstreamer_devel 
glib2_devel gtk2_devel 
glib2_devel libcroco_devel 
glib2_devel libgnome_devel 
glib2_devel libgnomeprint22_devel 
glib2_devel libgnomeui_devel 
glib2_devel libgsf_devel 
glib2_devel libIDL_devel 
glib2_devel libwnck_devel 
glib2_devel nautilus_cd_burner_devel 
glib2_devel ORBit2_devel 
glib2_devel ORBit2_devel 
glib2_devel pango_devel 
glibc sed 
glibc authconfig 
glibc prelink 
glibc bluez_bluefw 
glibc ppp 
glibc glibc_devel 
glibc glibc_headers 
glibc bind 
glibc bluez_hcidump 
glibc glibc_utils 
glibc sed 
glibc authconfig 
glibc prelink 
glibc bluez_bluefw 
glibc ppp 
glibc glibc_devel 
glibc glibc_headers 
glibc bind 
glibc bluez_hcidump 
glibc glibc_utils 
glibc_common glibc 
glibc_devel gcc 
glibc_devel compat_gcc_32 
glibc_devel gcc4 
glibc_devel nptl_devel 
glibc_headers glibc_devel 
glibc_headers glibc_devel 
glib_devel gtk+_devel 
glib_devel ORBit_devel 
gmp gmp_devel 
gnome_desktop gnome_desktop_devel 
gnome_desktop gnome_panel 
gnome_icon_theme gtkhtml3 
gnome_icon_theme control_center 
gnome_icon_theme evolution 
gnome_icon_theme nautilus 
gnome_keyring gnome_keyring_devel 
gnome_keyring gnome_panel 
gnome_keyring libgnomeui 
gnome_libs gnome_libs_devel 
gnome_mag gnome_mag_devel 
gnome_mag gnopernicus 
gnome_media gnome_volume_manager 
gnome_mime_data gnome_volume_manager 
gnome_mime_data gnome_vfs2 
gnome_netstatus gnome_applets 
gnome_panel gnome_applets 
gnome_panel gnome_panel_devel 
gnome_panel gnome_netstatus 
gnome_panel NetworkManager_gnome 
gnome_pilot evolution 
gnome_pilot gnome_pilot_conduits 
gnome_pilot gnome_pilot_devel 
gnome_python2 system_config_httpd 
gnome_python2 hwbrowser 
gnome_python2 gnome_python2_applet 
gnome_python2 gnome_python2_bonobo 
gnome_python2 gnome_python2_canvas 
gnome_python2 gnome_python2_gconf 
gnome_python2 gnome_python2_gnomeprint 
gnome_python2 gnome_python2_gnomevfs 
gnome_python2 gnome_python2_gtkhtml2 
gnome_python2 gnome_python2_nautilus 
gnome_python2 hal_gnome 
gnome_python2 rhn_applet 
gnome_python2 system_config_lvm 
gnome_python2 system_config_netboot 
gnome_python2 system_config_network 
gnome_python2 system_config_packages 
gnome_python2 system_config_printer_gui 
gnome_python2 up2date_gnome 
gnome_python2_bonobo gnome_python2 
gnome_python2_canvas system_config_httpd 
gnome_python2_canvas hwbrowser 
gnome_python2_canvas system_config_lvm 
gnome_python2_canvas system_config_netboot 
gnome_python2_canvas system_config_network 
gnome_python2_canvas system_config_printer_gui 
gnome_python2_canvas up2date_gnome 
gnome_python2_gtkhtml2 rhn_applet 
gnome_python2_gtkhtml2 system_config_printer_gui 
gnome_speech gnome_speech_devel 
gnome_speech dasher 
gnome_speech gnopernicus 
gnome_spell evolution 
gnome_vfs2 devhelp 
gnome_vfs2 eel2 
gnome_vfs2 gnome_python2_gnomevfs 
gnome_vfs2 gnome_vfs2_devel 
gnome_vfs2 gnome_vfs2_smb 
gnome_vfs2 gtkhtml2 
gnome_vfs2 libgnome 
gnome_vfs2 libgnomeui 
gnome_vfs2 nautilus 
gnome_vfs2 nautilus_cd_burner 
gnome_vfs2 openoffice.org 
gnome_vfs2 planner 
gnome_vfs2 yelp 
gnome_vfs2_devel devhelp_devel 
gnome_vfs2_devel eel2_devel 
gnome_vfs2_devel gnome_desktop_devel 
gnome_vfs2_devel gtkhtml2_devel 
gnome_vfs2_devel libgnome_devel 
gnome_vfs2_devel libgnomeui_devel 
gnome_vfs2_devel libgsf_devel 
gnome_vfs2_smb nautilus 
gnome_volume_manager gnome_session 
gnupg up2date 
gnuplot gnuplot_emacs 
gnuplot amanda_server 
gnuplot octave 
gnutls evolution 
gnutls evolution_connector 
gnutls gnutls_devel 
gnutls libsoup 
gok gok_devel 
gphoto2 gphoto2_devel 
gpm gpm_devel 
grep coreutils 
grep ash 
grep krb5_libs 
grep MAKEDEV 
grep pam 
grep mkinitrd 
grep prelink 
grep krb5_workstation 
grep logwatch 
grep irda_utils 
grep pdksh 
grep bc 
grep sysreport 
grep tcsh 
grep xorg_x11_libs 
grep nss_ldap 
grep nfs_utils 
grep amanda 
grep gphoto2 
grep krb5_server 
grep amanda_client 
grep amanda_server 
grep am_utils 
grep am_utils 
grep autofs 
grep caching_nameserver 
grep docbook_dtds 
grep FreeWnn 
grep inn 
grep mysql 
grep mysqlclient10 
grep ntp 
grep sgml_common 
grep sysstat 
grep xml_common 
grep zsh 
groff man 
groff linuxdoc_tools 
gsl gsl_devel 
gstreamer gstreamer_devel 
gstreamer gstreamer_plugins 
gstreamer nautilus_media 
gstreamer sound_juicer 
gstreamer_devel gstreamer_plugins_devel 
gstreamer_plugins gnome_applets 
gstreamer_plugins gstreamer_plugins_devel 
gstreamer_plugins nautilus_media 
gthumb gnome_volume_manager 
gtk+ gnome_libs 
gtk+ gtk+_devel 
gtk+ gtk_engines 
gtk+ imlib 
gtk+ nmap_frontend 
gtk+ xmms 
gtk2 libbonoboui 
gtk2 devhelp 
gtk2 gdm 
gtk2 libglade2 
gtk2 gnome_terminal 
gtk2 libwmf 
gtk2 at_spi 
gtk2 dia 
gtk2 eel2 
gtk2 ethereal_gnome 
gtk2 evolution 
gtk2 gail 
gtk2 gimp 
gtk2 gnome_keyring 
gtk2 gnome_netstatus 
gtk2 gnome_python2_canvas 
gtk2 gtk2_devel 
gtk2 gtk2_engines 
gtk2 gtkhtml2 
gtk2 libgail_gnome 
gtk2 libgcj 
gtk2 libgnomecanvas 
gtk2 libgnomeprintui22 
gtk2 libgnomeui 
gtk2 librsvg2 
gtk2 libwnck 
gtk2 planner 
gtk2 pygtk2 
gtk2 rhythmbox 
gtk2 tsclient 
gtk2 vino 
gtk2 yelp 
gtk2_devel libbonoboui_devel 
gtk2_devel devhelp_devel 
gtk2_devel eel2_devel 
gtk2_devel libglade2_devel 
gtk2_devel gnome_desktop_devel 
gtk2_devel gnome_panel_devel 
gtk2_devel gok_devel 
gtk2_devel libgnomeprintui22_devel 
gtk2_devel libwmf_devel 
gtk2_devel at_spi_devel 
gtk2_devel gail_devel 
gtk2_devel gimp_devel 
gtk2_devel gtkhtml2_devel 
gtk2_devel gtksourceview_devel 
gtk2_devel gtkspell_devel 
gtk2_devel libgnomecanvas_devel 
gtk2_devel libgnomeui_devel 
gtk2_devel librsvg2_devel 
gtk2_devel libwnck_devel 
gtk2_devel vte_devel 
gtk2_engines gnome_themes 
gtk+_devel gnome_libs_devel 
gtk+_devel imlib_devel 
gtk+_devel xmms_devel 
gtkhtml2 gnome_python2_gtkhtml2 
gtkhtml2 gtkhtml2_devel 
gtkhtml2 yelp 
gtkhtml3 gtkhtml3_devel 
gtkhtml3_devel evolution_devel 
gtksourceview gedit 
gtksourceview gtksourceview_devel 
gtksourceview_devel gedit_devel 
gtkspell gtkspell_devel 
guile guile_devel 
gzip mkinitrd 
gzip man 
gzip man_pages_ko 
gzip system_config_printer 
hal kudzu 
hal NetworkManager 
hal gnome_volume_manager 
hal hal_cups_utils 
hal hal_devel 
hal hal_gnome 
hal nautilus_cd_burner 
hal system_config_packages 
hal_cups_utils desktop_printing 
hesiod hesiod_devel 
hicolor_icon_theme gnome_icon_theme 
hicolor_icon_theme kdelibs 
hotplug udev 
hotplug pcmcia_cs 
hotplug gphoto2 
hotplug sane_backends 
hpoj hpoj_devel 
hpoj xojpanel 
htdig htdig_web 
htmlview pinfo 
htmlview gnome_libs 
htmlview system_config_date 
htmlview system_config_nfs 
htmlview system_config_samba 
htmlview system_config_services 
htmlview system_config_users 
htmlview system_logviewer 
htmlview xfig 
htmlview xpdf 
htmlview xscreensaver 
httpd httpd_devel 
httpd httpd_manual 
httpd httpd_suexec 
httpd system_config_httpd 
httpd mod_auth_pgsql 
httpd mod_perl 
httpd mod_python 
httpd mod_ssl 
httpd squirrelmail 
httpd squirrelmail 
httpd_devel mod_perl_devel 
httpd_suexec httpd 
hwdata usbutils 
hwdata hotplug 
hwdata kudzu 
hwdata kudzu 
hwdata pciutils 
hwdata pcmcia_cs 
hwdata system_config_display 
hwdata system_config_kickstart 
iiimf_csconv iiimf_server 
iiimf_libs iiimf_gtk 
iiimf_libs iiimf_libs_devel 
iiimf_libs iiimf_x 
iiimf_server iiimf_le_canna 
iiimf_server iiimf_le_hangul 
iiimf_server iiimf_le_sun_thai 
iiimf_server iiimf_le_unit 
iiimf_server iiimf_le_xcin 
ImageMagick ImageMagick_c++ 
ImageMagick ImageMagick_c++_devel 
ImageMagick ImageMagick_devel 
ImageMagick ImageMagick_perl 
ImageMagick xfig 
ImageMagick_c++ ImageMagick_c++_devel 
ImageMagick_devel ImageMagick_c++_devel 
imlib gnome_libs 
imlib imlib_devel 
imlib_devel gnome_libs_devel 
indent ORBit2_devel 
indent ORBit_devel 
indexhtml lynx 
inews inn 
info tar 
info emacspeak 
info a2ps 
info gdb 
info octave 
initscripts pam 
initscripts kernel 
initscripts kbd 
initscripts dhclient 
initscripts dhcpv6_client 
initscripts ipsec_tools 
initscripts isdn4k_utils 
initscripts openssh 
initscripts portmap 
initscripts quota 
initscripts rp_pppoe 
initscripts system_config_network_tui 
initscripts xinetd 
initscripts glibc_kernheaders 
initscripts quagga 
initscripts amanda 
initscripts aumix 
initscripts bluez_utils 
initscripts foomatic 
initscripts kernel_hugemem 
initscripts kernel_smp 
initscripts postgresql 
initscripts pvm 
initscripts radvd 
initscripts rhgb 
initscripts samba 
initscripts system_config_packages 
initscripts system_config_printer 
initscripts xorg_x11_xfs 
inn inn_devel 
intltool scrollkeeper 
iproute NetworkManager 
iptables iptstate 
iptables system_config_securitylevel_tui 
iptables iptables_devel 
iptables iptables_ipv6 
isdn4k_utils isdn4k_utils_devel 
isdn4k_utils isdn4k_utils_vboxgetty 
isdn4k_utils xisdnload 
jadetex docbook_utils_pdf 
jadetex docbook_utils 
java_1.4.2_gcj_compat java_1.4.2_gcj_compat_devel 
katana ecj 
katana katana_build 
kdeaddons kdeaddons_atlantikdesigner 
kdeaddons kdeaddons_xmms 
kdeartwork kdeartwork_icons 
kdebase kdeartwork 
kdebase kdeaddons 
kdebase kdeadmin 
kdebase kdebase_devel 
kdebase kdegames 
kdebase kdegraphics 
kdebase kdemultimedia 
kdebase kdenetwork 
kdebase kdepim 
kdebase kdeutils 
kdebase_devel kdeutils_devel 
kdebase_devel kdegames_devel 
kdebase_devel kdemultimedia_devel 
kdegames kdeaddons_atlantikdesigner 
kdegames kdeaddons_xmms 
kdegames kdegames_devel 
kdegraphics kdegraphics_devel 
kdelibs kdeartwork 
kdelibs kde_i18n_Bengali 
kdelibs kde_i18n_Brazil 
kdelibs kde_i18n_British 
kdelibs kde_i18n_Bulgarian 
kdelibs kde_i18n_Catalan 
kdelibs kde_i18n_Chinese 
kdelibs kde_i18n_Chinese_Big5 
kdelibs kde_i18n_Czech 
kdelibs kde_i18n_Danish 
kdelibs kde_i18n_Dutch 
kdelibs kde_i18n_Estonian 
kdelibs kde_i18n_Finnish 
kdelibs kde_i18n_French 
kdelibs kde_i18n_German 
kdelibs kde_i18n_Greek 
kdelibs kde_i18n_Hebrew 
kdelibs kde_i18n_Hindi 
kdelibs kde_i18n_Hungarian 
kdelibs kde_i18n_Icelandic 
kdelibs kde_i18n_Italian 
kdelibs kde_i18n_Japanese 
kdelibs kde_i18n_Norwegian 
kdelibs kde_i18n_Norwegian_Nynorsk 
kdelibs kde_i18n_Polish 
kdelibs kde_i18n_Portuguese 
kdelibs kde_i18n_Punjabi 
kdelibs kde_i18n_Romanian 
kdelibs kde_i18n_Russian 
kdelibs kde_i18n_Serbian 
kdelibs kde_i18n_Slovak 
kdelibs kde_i18n_Slovenian 
kdelibs kde_i18n_Spanish 
kdelibs kde_i18n_Swedish 
kdelibs kde_i18n_Tamil 
kdelibs kde_i18n_Turkish 
kdelibs kde_i18n_Ukrainian 
kdelibs kdeaddons 
kdelibs kdeadmin 
kdelibs kdebase 
kdelibs kdegames 
kdelibs kdegraphics 
kdelibs kdelibs_devel 
kdelibs kdemultimedia 
kdelibs kdenetwork 
kdelibs kdeutils 
kdelibs openoffice.org_kde 
kdelibs_devel kdenetwork_devel 
kdelibs_devel kdesdk_devel 
kdelibs_devel kdevelop 
kdelibs_devel kdebase_devel 
kdelibs_devel kdepim_devel 
kdemultimedia kdemultimedia_devel 
kdenetwork kdenetwork_devel 
kdenetwork kdenetwork_nowlistening 
kdepim kdepim_devel 
kdesdk kdesdk_devel 
kdeutils kdeutils_devel 
kernel lvm2 
kernel initscripts 
kernel prelink 
kernel selinux_policy_targeted 
kernel iptables 
kernel libpcap 
kernel pciutils 
kernel pcmcia_cs 
kernel nfs_utils 
kernel quota 
kernel rp_pppoe 
kernel tcpdump 
kernel vconfig 
kernel dhcp 
kernel gnome_volume_manager 
kernel arptables_jf 
kernel selinux_policy_targeted_sources 
kernel sysstat 
kernel_utils lm_sensors 
krb5_devel openssl_devel 
krb5_libs krb5_workstation 
krb5_libs freeradius 
krb5_libs krb5_server 
krb5_libs krb5_devel 
krbafs krbafs_devel 
krbafs krbafs_utils 
kudzu system_config_mouse 
kudzu kernel_utils 
kudzu pcmcia_cs 
kudzu system_config_network_tui 
kudzu hwbrowser 
kudzu anaconda 
kudzu system_config_display 
kudzu system_config_soundcard 
less gzip 
less man 
less octave 
libacl libacl_devel 
libaio libaio_devel 
libaio_devel lam 
libao libao_devel 
libao vorbis_tools 
libart_lgpl libbonoboui 
libart_lgpl dia 
libart_lgpl eel2 
libart_lgpl libart_lgpl_devel 
libart_lgpl libgcj 
libart_lgpl libgnomeui 
libart_lgpl librsvg2 
libart_lgpl openoffice.org 
libart_lgpl_devel libbonoboui_devel 
libart_lgpl_devel eel2_devel 
libart_lgpl_devel kdelibs_devel 
libart_lgpl_devel libgnomecanvas_devel 
libart_lgpl_devel libgnomeprint22_devel 
libart_lgpl_devel libgnomeui_devel 
libart_lgpl_devel librsvg2_devel 
libattr libattr_devel 
libattr vim_X11 
libattr_devel libacl_devel 
libavc1394 libavc1394_devel 
libavc1394 pwlib 
libbonobo libbonoboui 
libbonobo at_spi 
libbonobo gnome_python2_bonobo 
libbonobo libbonobo_devel 
libbonobo libgnome 
libbonobo libgnomeui 
libbonobo yelp 
libbonobo_devel libbonoboui_devel 
libbonobo_devel evolution_data_server_devel 
libbonobo_devel gnome_speech_devel 
libbonobo_devel gok_devel 
libbonobo_devel at_spi_devel 
libbonobo_devel gnome_mag_devel 
libbonobo_devel gnome_vfs2_devel 
libbonobo_devel libgnome_devel 
libbonobo_devel libgnomeprint22_devel 
libbonobo_devel libgnomeui_devel 
libbonoboui libbonoboui_devel 
libbonoboui evolution 
libbonoboui gnome_python2_bonobo 
libbonoboui gnome_spell 
libbonoboui libgnomeui 
libbonoboui_devel gnome_panel_devel 
libbonoboui_devel libgnomeui_devel 
libcap vsftpd 
libcap libcap_devel 
libcap ntp 
libcap zsh 
libc_client libc_client_devel 
libcroco libcroco_devel 
libcroco librsvg2 
libcroco_devel librsvg2_devel 
libdbi libdbi_dbd_mysql 
libdbi libdbi_dbd_pgsql 
libdbi libdbi_devel 
libdv libdv_devel 
libdv libdv_tools 
libdv pwlib 
libexif libexif_devel 
libexif nautilus 
libexif_devel gphoto2_devel 
libexif_devel ImageMagick_devel 
libf2c gcc_g77 
libgail_gnome control_center 
libgail_gnome gnopernicus 
libgal2 evolution 
libgal2 libgal2_devel 
libgal2_devel evolution_devel 
libgcc gcc 
libgcc compat_gcc_32 
libgcc glibc 
libgcc gcc4 
libgcj java_1.4.2_gcj_compat 
libgcj ecj 
libgcj gcc_java 
libgcj libgcj_devel 
libgcj_devel gcc_java 
libgcrypt libgcrypt_devel 
libgcrypt vino 
libgfortran gcc4_gfortran 
libglade2 system_config_httpd 
libglade2 libbonoboui 
libglade2 devhelp 
libglade2 gdm 
libglade2 libglade2_devel 
libglade2 gnome_netstatus 
libglade2 gnome_spell 
libglade2 libgnomeui 
libglade2 NetworkManager_gnome 
libglade2 planner 
libglade2 system_config_network 
libglade2 system_config_packages 
libglade2 system_switch_im 
libglade2 system_switch_mail_gnome 
libglade2 vino 
libglade2 yelp 
libglade2_devel libbonoboui_devel 
libglade2_devel gtkhtml3_devel 
libglade2_devel libgal2_devel 
libglade2_devel libgnomecanvas_devel 
libglade2_devel libgnomeui_devel 
libgnat gcc_gnat 
libgnome libbonoboui 
libgnome dia 
libgnome gaim 
libgnome gnomemeeting 
libgnome libgnome_devel 
libgnome libgnomeui 
libgnome rhn_applet 
libgnomecanvas libbonoboui 
libgnomecanvas gdm 
libgnomecanvas gail 
libgnomecanvas gnome_python2_canvas 
libgnomecanvas libgal2 
libgnomecanvas libgnomecanvas_devel 
libgnomecanvas libgnomeprintui22 
libgnomecanvas libgnomeui 
libgnomecanvas_devel libbonoboui_devel 
libgnomecanvas_devel libgnomeprintui22_devel 
libgnomecanvas_devel gail_devel 
libgnomecanvas_devel libgal2_devel 
libgnomecanvas_devel libgnomeui_devel 
libgnomecups libgnomecups_devel 
libgnomecups libgnomeprint22 
libgnome_devel libbonoboui_devel 
libgnome_devel evolution_data_server_devel 
libgnome_devel gnome_desktop_devel 
libgnome_devel libgnomeui_devel 
libgnomeprint22 gtkhtml3 
libgnomeprint22 gnome_python2_gnomeprint 
libgnomeprint22 gpdf 
libgnomeprint22 libgnomeprint22_devel 
libgnomeprint22 libgnomeprintui22 
libgnomeprint22_devel gtkhtml3_devel 
libgnomeprint22_devel libgnomeprintui22_devel 
libgnomeprint22_devel gtksourceview_devel 
libgnomeprint22_devel libgal2_devel 
libgnomeprintui22 gedit 
libgnomeprintui22 libgnomeprintui22_devel 
libgnomeprintui22 gnome_python2_gnomeprint 
libgnomeprintui22 gpdf 
libgnomeprintui22 planner 
libgnomeprintui22_devel gtkhtml3_devel 
libgnomeprintui22_devel libgal2_devel 
libgnomeui devhelp 
libgnomeui gdm 
libgnomeui gedit 
libgnomeui gnome_system_monitor 
libgnomeui dia 
libgnomeui eel2 
libgnomeui gnomemeeting 
libgnomeui gnome_netstatus 
libgnomeui gnome_spell 
libgnomeui libgail_gnome 
libgnomeui libgnomeui_devel 
libgnomeui planner 
libgnomeui rhn_applet 
libgnomeui rhythmbox 
libgnomeui sound_juicer 
libgnomeui vino 
libgnomeui yelp 
libgnomeui_devel devhelp_devel 
libgnomeui_devel eel2_devel 
libgnomeui_devel gnome_desktop_devel 
libgnomeui_devel gnome_panel_devel 
libgnomeui_devel gok_devel 
libgnomeui_devel gtkhtml3_devel 
libgnomeui_devel gnome_pilot_devel 
libgnomeui_devel libcroco_devel 
libgnomeui_devel libgal2_devel 
libgpg_error libgpg_error_devel 
libgpg_error_devel libgcrypt_devel 
libgsf libgsf_devel 
libgsf librsvg2 
libgsf_devel librsvg2_devel 
libgtop2 gnome_system_monitor 
libgtop2 libgtop2_devel 
libIDL libIDL_devel 
libIDL pyorbit 
libIDL_devel ORBit2_devel 
libidn libidn_devel 
libidn_devel curl_devel 
libidn_devel kdelibs_devel 
libieee1284 libieee1284_devel 
libieee1284_devel sane_backends_devel 
libjpeg libtiff 
libjpeg emacs 
libjpeg imlib 
libjpeg libgnomeui 
libjpeg libjpeg_devel 
libjpeg libmng 
libjpeg_devel ImageMagick_c++_devel 
libjpeg_devel ImageMagick_devel 
libjpeg_devel imlib_devel 
libjpeg_devel kdelibs_devel 
libjpeg_devel libmng_devel 
libjpeg_devel qt_devel 
libmng libmng_devel 
libmng_devel qt_devel 
libmudflap libmudflap_devel 
libmusicbrainz libmusicbrainz_devel 
libmusicbrainz sound_juicer 
libobjc gcc_objc 
libogg libogg_devel 
libogg libvorbis 
libogg vorbis_tools 
libogg_devel libtheora_devel 
libogg_devel libvorbis_devel 
libpcap ppp 
libpcap ethereal 
libpng10 libpng10_devel 
libpng emacs 
libpng ghostscript 
libpng gnuplot 
libpng libpng_devel 
libpng librsvg2 
libpng_devel ImageMagick_c++_devel 
libpng_devel ImageMagick_devel 
libpng_devel pilot_link_devel 
libpng_devel qt_devel 
libraw1394 libraw1394_devel 
libraw1394 pwlib 
libraw1394_devel libavc1394_devel 
librsvg2 gdm 
librsvg2 eel2 
librsvg2 librsvg2_devel 
librsvg2_devel eel2_devel 
libselinux dbus 
libselinux pam 
libselinux policycoreutils 
libselinux SysVinit 
libselinux udev 
libselinux hal 
libselinux nscd 
libselinux openssh 
libselinux vixie_cron 
libselinux libselinux_devel 
libselinux system_config_securitylevel 
libsepol checkpolicy 
libsepol policycoreutils 
libsepol SysVinit 
libsepol libsepol_devel 
libsilc libsilc_devel 
libsilc libsilc_doc 
libsoup evolution 
libsoup evolution_connector 
libsoup evolution_data_server 
libsoup evolution_webcal 
libsoup libsoup_devel 
libsoup_devel evolution_devel 
libstdc++ gcc_c++ 
libstdc++ gcc4_c++ 
libstdc++ pwlib 
libstdc++ libstdc++_devel 
libstdc++_devel gcc_c++ 
libstdc++_devel gcc4_c++ 
libstdc++_devel libmusicbrainz_devel 
libtabe libtabe_devel 
libtabe xcin 
libtermcap slang 
libtermcap libtermcap_devel 
libtermcap_devel readline_devel 
libtermcap_devel slang_devel 
libtheora libtheora_devel 
libtheora theora_tools 
libtiff emacs 
libtiff gtk2 
libtiff imlib 
libtiff libtiff_devel 
libtiff_devel ImageMagick_c++_devel 
libtiff_devel ImageMagick_devel 
libtiff_devel imlib_devel 
libtiff_devel kdelibs_devel 
libtool_libs libtool 
libungif emacs 
libungif libungif_devel 
libungif libungif_progs 
libungif_devel imlib_devel 
libusb libusb_devel 
libusb_devel sane_backends_devel 
libuser libuser_devel 
libuser firstboot 
libuser system_config_rootpassword 
libuser system_config_samba 
libuser system_config_users 
libvorbis libvorbis_devel 
libvorbis vorbis_tools 
libvorbis_devel arts_devel 
libwmf libwmf_devel 
libwnck gnome_system_monitor 
libwnck gnome_panel 
libwnck libwnck_devel 
libwnck_devel gok_devel 
libwvstreams libwvstreams_devel 
libxklavier gnome_applets 
libxklavier control_center 
libxklavier libxklavier_devel 
libxml2 libxslt 
libxml2 libxml2_python 
libxml2 xmlsec1 
libxml2 xmlsec1_openssl 
libxml2 libbonoboui 
libxml2 docbook_slides 
libxml2 gdm 
libxml2 libglade2 
libxml2 libwmf 
libxml2 alchemist 
libxml2 dia 
libxml2 docbook_dtds 
libxml2 docbook_simple 
libxml2 eel2 
libxml2 gstreamer 
libxml2 gtkhtml2 
libxml2 kdebase 
libxml2 libcroco 
libxml2 libcroco_devel 
libxml2 libgnome 
libxml2 libgnomeui 
libxml2 librsvg2 
libxml2 libsoup 
libxml2 libxml2_devel 
libxml2 libxslt_python 
libxml2 scrollkeeper 
libxml2 shared_mime_info 
libxml2 xhtml1_dtds 
libxml2 yelp 
libxml2_devel libbonoboui_devel 
libxml2_devel eel2_devel 
libxml2_devel libglade2_devel 
libxml2_devel libwmf_devel 
libxml2_devel GConf2_devel 
libxml2_devel gstreamer_devel 
libxml2_devel gtkhtml2_devel 
libxml2_devel gtksourceview_devel 
libxml2_devel ImageMagick_c++_devel 
libxml2_devel ImageMagick_devel 
libxml2_devel libbonobo_devel 
libxml2_devel libcroco_devel 
libxml2_devel libgnome_devel 
libxml2_devel libgnomeprint22_devel 
libxml2_devel libgnomeui_devel 
libxml2_devel libgsf_devel 
libxml2_devel librsvg2_devel 
libxml2_devel libxslt_devel 
libxml2_devel xmlsec1_devel 
libxml2_devel xmlsec1_openssl_devel 
libxml2_python up2date 
libxml2_python anaconda 
libxml2_python anaconda_runtime 
libxml2_python libxslt_python 
libxml2_python system_config_packages 
libxslt xmlsec1 
libxslt xmlsec1_openssl 
libxslt gtk_doc 
libxslt alchemist 
libxslt dia 
libxslt libgnome 
libxslt libxslt_devel 
libxslt libxslt_python 
libxslt planner 
libxslt scrollkeeper 
libxslt xmlto 
libxslt yelp 
libxslt_devel kdelibs_devel 
libxslt_devel libgnome_devel 
libxslt_devel xmlsec1_devel 
libxslt_devel xmlsec1_openssl_devel 
linuxwacom linuxwacom_devel 
lm_sensors lm_sensors_devel 
lockdev minicom 
lockdev gphoto2 
lockdev lockdev_devel 
lockdev uucp 
logrotate ppp 
logrotate vsftpd 
logrotate samba 
logrotate squid 
lvm2 udev 
lvm2 mkinitrd 
lvm2 system_config_lvm 
m4 autoconf213 
m4 autoconf 
m4 bison 
m4 libtool 
m4 selinux_policy_targeted_sources 
m4 sendmail_cf 
m4 system_config_printer 
mailcap mutt 
mailx logwatch 
make nss_db 
make stunnel 
make kdevelop 
make mod_ssl 
make openldap_servers 
make selinux_policy_targeted_sources 
make ypserv 
MAKEDEV udev 
MAKEDEV udev 
metacity firstboot 
metacity system_config_display 
mgetty mgetty_sendfax 
mgetty mgetty_voice 
mikmod mikmod_devel 
mingetty initscripts 
mkinitrd kernel 
mkinitrd mkbootdisk 
mkinitrd up2date 
mkinitrd kernel_hugemem 
mkinitrd kernel_smp 
mkinitrd lilo 
mkisofs dvd+rw_tools 
mkisofs k3b 
mkisofs nautilus_cd_burner 
mkisofs xcdroast 
mktemp bash 
mktemp grub 
mktemp gzip 
mktemp openssl 
mktemp MAKEDEV 
mktemp pam 
mktemp initscripts 
mktemp mkinitrd 
mktemp openldap 
mktemp kbd 
mktemp groff 
mktemp man 
mktemp mgetty 
mktemp nss_ldap 
mktemp autoconf213 
mktemp autoconf 
mktemp autofs 
mktemp libtool 
mktemp mailman 
mktemp mgetty_sendfax 
mktemp openssl096b 
mktemp taipeifonts 
mod_perl mod_perl_devel 
module_init_tools kernel 
module_init_tools kernel_hugemem 
module_init_tools kernel_smp 
mozilla devhelp 
mozilla mozilla_chat 
mozilla mozilla_devel 
mozilla mozilla_dom_inspector 
mozilla mozilla_js_debugger 
mozilla mozilla_mail 
mozilla_nspr mozilla 
mozilla_nspr mozilla_nspr_devel 
mozilla_nspr mozilla_nss 
mozilla_nspr_devel mozilla_devel 
mozilla_nspr_devel mozilla_nss_devel 
mozilla_nss mozilla 
mozilla_nss mozilla_nss_devel 
mozilla_nss_devel mozilla_devel 
mpage system_config_printer 
mtools syslinux 
mtr mtr_gtk 
mx MySQL_python 
mx postgresql_python 
mysql freeradius_mysql 
mysql mysql_bench 
mysql mysql_devel 
mysql mysql_server 
mysqlclient10 mysqlclient10_devel 
mysqlclient10 MySQL_python 
nautilus gnome_python2_nautilus 
nautilus_cd_burner nautilus 
nautilus_cd_burner nautilus_cd_burner_devel 
ncurses ncurses_devel 
ncurses quagga 
ncurses emacs_nox 
ncurses emacs 
ncurses joe 
ncurses tn5250 
ncurses_devel vte_devel 
neon neon_devel 
netpbm netpbm_devel 
netpbm netpbm_progs 
netpbm_progs mgetty_sendfax 
netpbm_progs tetex_latex 
net_snmp freeradius 
net_snmp ethereal 
net_snmp hpoj 
net_snmp net_snmp_devel 
net_snmp net_snmp_perl 
net_snmp net_snmp_utils 
net_snmp_utils freeradius 
net_tools initscripts 
NetworkManager NetworkManager_gnome 
newt system_config_mouse 
newt up2date 
newt system_config_network_tui 
newt newt_devel 
newt system_config_date 
newt system_config_printer 
newt system_switch_mail 
newt_perl crypto_utils 
nfs_utils system_config_nfs 
nmap nmap_frontend 
nscd nss_ldap 
nss_db nss_db_compat 
ntp system_config_date 
Omni Omni_foomatic 
Omni_foomatic system_config_printer 
openh323 gnomemeeting 
openh323 openh323_devel 
openjade docbook_dtds 
openjade docbook_style_dsssl 
openjade docbook_style_dsssl 
openjade openjade_devel 
openjade perl_SGMLSpm 
openldap sendmail 
openldap compat_openldap 
openldap evolution_connector 
openldap exim 
openldap mod_authz_ldap 
openldap openldap_clients 
openldap openldap_devel 
openldap openldap_servers 
openldap postfix 
openldap python_ldap 
openldap_devel apr_util_devel 
openldap_servers openldap_servers_sql 
openmotif ddd 
openmotif openmotif_devel 
openoffice.org openoffice.org_i18n 
openoffice.org openoffice.org_kde 
openoffice.org openoffice.org_libs 
openoffice.org_libs openoffice.org 
openoffice.org_libs openoffice.org_kde 
openssh openssh_clients 
openssh openssh_server 
openssh openssh_askpass 
openssh openssh_askpass_gnome 
openssh_clients lam 
openssh_server lam 
openssl xmlsec1_openssl 
openssl libpcap 
openssl NetworkManager 
openssl sendmail 
openssl curl 
openssl vsftpd 
openssl crypto_utils 
openssl dovecot 
openssl exim 
openssl kdelibs 
openssl mod_ssl 
openssl openldap_servers 
openssl openssl_devel 
openssl openssl_perl 
openssl perl_Crypt_SSLeay 
openssl postfix 
openssl xmlsec1_openssl_devel 
openssl xmlsec1_openssl 
openssl libpcap 
openssl NetworkManager 
openssl sendmail 
openssl curl 
openssl vsftpd 
openssl crypto_utils 
openssl dovecot 
openssl exim 
openssl kdelibs 
openssl mod_ssl 
openssl openldap_servers 
openssl openssl_devel 
openssl openssl_perl 
openssl perl_Crypt_SSLeay 
openssl postfix 
openssl xmlsec1_openssl_devel 
openssl_devel curl_devel 
openssl_devel cups_devel 
openssl_devel kdelibs_devel 
openssl_devel neon_devel 
openssl_devel pwlib_devel 
openssl_devel xmlsec1_devel 
openssl_devel xmlsec1_openssl_devel 
oprofile oprofile_devel 
ORBit gnome_libs 
ORBit ORBit_devel 
ORBit2 libbonoboui 
ORBit2 at_spi 
ORBit2 evolution 
ORBit2 evolution 
ORBit2 evolution_data_server 
ORBit2 GConf2 
ORBit2 libgnome 
ORBit2 libgnomeui 
ORBit2 ORBit2_devel 
ORBit2 pyorbit 
ORBit2_devel libbonoboui_devel 
ORBit2_devel at_spi_devel 
ORBit2_devel GConf2_devel 
ORBit2_devel gnome_pilot_devel 
ORBit2_devel libbonobo_devel 
ORBit2_devel libgnome_devel 
ORBit2_devel libgnomeui_devel 
ORBit_devel gnome_libs_devel 
pam coreutils 
pam authconfig 
pam SysVinit 
pam util_linux 
pam udev 
pam kudzu 
pam passwd 
pam usermode 
pam kbd 
pam pam_ccreds 
pam vixie_cron 
pam quagga 
pam vsftpd 
pam gdm 
pam libc_client 
pam pam_devel 
pam rsh_server 
pam samba 
pam up2date_gnome 
pam vlock 
pango gnome_terminal 
pango dia 
pango eel2 
pango gimp 
pango gtk2 
pango libgnomeprint22 
pango libgnomeui 
pango pango_devel 
pango_devel gtk2_devel 
pango_devel libgnomeprint22_devel 
pango_devel libgnomeui_devel 
pango_devel libwnck_devel 
parted anaconda 
parted parted_devel 
parted pyparted 
passivetex xmlto 
passwd usermode 
patch intltool 
patch rpm_build 
pciutils system_config_network_tui 
pciutils_devel kudzu_devel 
pcre grep 
pcre pcre_devel 
pcre postfix 
pcre_devel httpd_devel 
pcre_devel kdelibs_devel 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl 
perl perl_Filter 
perl up2date 
perl vim_enhanced 
perl httpd_devel 
perl quagga_contrib 
perl kdevelop 
perl linuxdoc_tools 
perl linuxdoc_tools 
perl lm_sensors 
perl amanda_server 
perl autoconf213 
perl autoconf 
perl autoconf 
perl autoconf 
perl autoconf 
perl automake14 
perl automake15 
perl automake15 
perl automake16 
perl automake16 
perl automake16 
perl automake17 
perl automake17 
perl automake17 
perl automake17 
perl automake 
perl automake 
perl automake 
perl automake 
perl crypto_utils 
perl cyrus_imapd 
perl docbook_dtds 
perl emacs_common 
perl foomatic 
perl gaim 
perl gd_progs 
perl ImageMagick_perl 
perl ImageMagick_perl 
perl inn 
perl inn 
perl inn 
perl inn 
perl kdelibs 
perl libgnomeprint22 
perl libtool 
perl mgetty_sendfax 
perl mod_perl 
perl mod_perl 
perl mod_perl 
perl mod_perl 
perl mozilla 
perl mrtg 
perl mrtg 
perl mrtg 
perl mrtg 
perl mrtg 
perl net_snmp_perl 
perl openoffice.org 
perl openssl_perl 
perl perl_Convert_ASN1 
perl perl_Crypt_SSLeay 
perl perl_DateManip 
perl perl_DateManip 
perl perl_DBD_MySQL 
perl perl_DBD_MySQL 
perl perl_DBD_Pg 
perl perl_DBD_Pg 
perl perl_DBI 
perl perl_DBI 
perl perl_DBI 
perl perl_HTML_Parser 
perl perl_HTML_Parser 
perl perl_HTML_Tagset 
perl perl_HTML_Tagset 
perl perl_libwww_perl 
perl perl_libwww_perl 
perl perl_libwww_perl 
perl perl_libwww_perl 
perl perl_libxml_enno 
perl perl_libxml_perl 
perl perl_libxml_perl 
perl perl_Parse_Yapp 
perl perl_Parse_Yapp 
perl perl_SGMLSpm 
perl perl_suidperl 
perl perl_Time_HiRes 
perl perl_URI 
perl perl_XML_Dumper 
perl perl_XML_Dumper 
perl perl_XML_Encoding 
perl perl_XML_Encoding 
perl perl_XML_Grove 
perl perl_XML_Grove 
perl perl_XML_Parser 
perl perl_XML_Parser 
perl perl_XML_Twig 
perl rhn_applet 
perl rpm_build 
perl spamassassin 
perl squid 
perl squirrelmail 
perl squirrelmail 
perl subversion 
perl system_config_printer 
perl system_config_printer 
perl tetex 
perl tetex_latex 
perl xscreensaver 
perl_Convert_ASN1 perl_LDAP 
perl_Cyrus cyrus_imapd_utils 
perl_Date_Calc postfix_pflogsumm 
perl_DBD_MySQL mysql_server 
perl_DBI mysql_server 
perl_DBI perl_DBD_MySQL 
perl_DBI perl_DBD_Pg 
perl_HTML_Parser perl_libwww_perl 
perl_HTML_Tagset perl_HTML_Parser 
perl_libwww_perl perl_XML_Parser 
perl_libxml_enno foomatic 
perl_libxml_perl foomatic 
perl_Parse_Yapp foomatic 
perl_SGMLSpm docbook_utils 
perl_URI perl_XML_Parser 
perl_XML_Dumper foomatic 
perl_XML_Encoding foomatic 
perl_XML_LibXML_Common perl_XML_LibXML 
perl_XML_NamespaceSupport perl_XML_LibXML 
perl_XML_Parser foomatic 
perl_XML_Parser intltool 
perl_XML_Parser perl_libxml_perl 
perl_XML_Parser perl_XML_Dumper 
perl_XML_SAX perl_XML_LibXML 
php php_devel 
php php_domxml 
php php_gd 
php php_imap 
php php_ldap 
php php_mbstring 
php php_mysql 
php php_ncurses 
php php_odbc 
php php_pear 
php php_pgsql 
php php_snmp 
php php_xmlrpc 
php squirrelmail 
php_pear php 
pilot_link gnome_pilot 
pilot_link pilot_link_devel 
pilot_link_devel gnome_pilot_devel 
pkgconfig libidn_devel 
pkgconfig gphoto2_devel 
pkgconfig alsa_lib_devel 
pkgconfig audiofile_devel 
pkgconfig glib2_devel 
pkgconfig libcroco_devel 
pkgconfig libIDL_devel 
pkgconfig libsilc_devel 
pkgconfig xorg_x11_devel 
pnm2ppa system_config_printer 
policycoreutils setools 
policycoreutils selinux_policy_targeted 
policycoreutils selinux_policy_targeted_sources 
popt rpm 
popt gstreamer 
popt librsvg2 
popt planner 
portmap nfs_utils 
portmap ypbind 
portmap am_utils 
portmap bootparamd 
portmap rusers_server 
portmap ypserv 
postgresql freeradius_postgresql 
postgresql postgresql_contrib 
postgresql postgresql_pl 
postgresql postgresql_server 
postgresql postgresql_test 
postgresql_libs postgresql_devel 
postgresql_libs postgresql_odbc 
postgresql_server postgresql_pl 
postgresql_server postgresql_test 
ppp rp_pppoe 
ppp wvdial 
procmail sendmail 
procmail spamassassin 
psmisc tmpwatch 
psutils a2ps 
psutils tetex_dvips 
pvm pvm_gui 
pwlib gnomemeeting 
pwlib openh323 
pwlib pwlib_devel 
pwlib_devel openh323_devel 
pygtk2 system_config_httpd 
pygtk2 hwbrowser 
pygtk2 firstboot 
pygtk2 gnome_python2_canvas 
pygtk2 hal_gnome 
pygtk2 pygtk2_devel 
pygtk2 pygtk2_libglade 
pygtk2 rhn_applet 
pygtk2 switchdesk_gui 
pygtk2 system_config_boot 
pygtk2 system_config_display 
pygtk2 system_config_kickstart 
pygtk2 system_config_language 
pygtk2 system_config_lvm 
pygtk2 system_config_netboot 
pygtk2 system_config_network 
pygtk2 system_config_nfs 
pygtk2 system_config_packages 
pygtk2 system_config_printer_gui 
pygtk2 system_config_rootpassword 
pygtk2 system_config_samba 
pygtk2 system_config_securitylevel 
pygtk2 system_config_services 
pygtk2 system_config_soundcard 
pygtk2 system_config_users 
pygtk2 system_logviewer 
pygtk2 system_switch_im 
pygtk2 system_switch_mail_gnome 
pygtk2 up2date_gnome 
pygtk2_libglade system_config_httpd 
pygtk2_libglade hwbrowser 
pygtk2_libglade authconfig_gtk 
pygtk2_libglade rhn_applet 
pygtk2_libglade system_config_display 
pygtk2_libglade system_config_kickstart 
pygtk2_libglade system_config_lvm 
pygtk2_libglade system_config_netboot 
pygtk2_libglade system_config_network 
pygtk2_libglade system_config_packages 
pygtk2_libglade system_config_printer_gui 
pygtk2_libglade system_config_samba 
pygtk2_libglade system_config_services 
pygtk2_libglade system_config_users 
pygtk2_libglade system_switch_im 
pygtk2_libglade system_switch_mail_gnome 
pygtk2_libglade up2date_gnome 
pyOpenSSL rhnlib 
pyorbit gnome_python2_bonobo 
pyorbit gnome_python2_nautilus 
pyorbit pyorbit_devel 
pyparted hwbrowser 
pyparted anaconda 
PyQt PyQt_devel 
PyQt PyQt_examples 
python rhpl 
python authconfig 
python pyOpenSSL 
python rhnlib 
python rpm_python 
python up2date 
python system_config_network_tui 
python system_config_httpd 
python system_config_httpd 
python 4Suite 
python anaconda_runtime 
python beecrypt_python 
python bg5ps 
python firstboot 
python katana_build 
python mailman 
python mx 
python MySQL_python 
python MySQL_python 
python postgresql_python 
python PyQt 
python python_devel 
python python_docs 
python python_ldap 
python python_ldap 
python python_tools 
python PyXML 
python rhn_applet 
python selinux_policy_targeted_sources 
python sip 
python switchdesk_gui 
python system_config_kickstart 
python system_config_lvm 
python system_config_packages 
python system_config_printer 
python system_config_samba 
python system_switch_im 
python system_switch_mail 
python system_switch_mail_gnome 
python tkinter 
python_devel Pyrex 
python_devel Pyrex 
python_devel sip_devel 
pyxf86config rhpl 
pyxf86config system_config_mouse 
pyxf86config system_config_display 
pyxf86config system_config_keyboard 
PyXML 4Suite 
PyXML system_config_printer 
qt kdeartwork 
qt kdelibs 
qt PyQt 
qt qt_config 
qt qt_devel 
qt qt_MySQL 
qt qt_ODBC 
qt qt_PostgreSQL 
qt unixODBC_kde 
qt_designer kdevelop 
qt_devel kdelibs_devel 
qt_devel qt_designer 
rdesktop tsclient 
readline quagga 
readline guile 
readline readline_devel 
readline_devel pilot_link_devel 
redhat_artwork gdm 
redhat_artwork gnome_session 
redhat_artwork firstboot 
redhat_artwork gnome_desktop 
redhat_artwork kdebase 
redhat_artwork kdelibs 
redhat_artwork metacity 
redhat_artwork nautilus 
redhat_artwork system_config_display 
redhat_logos firstboot 
redhat_logos redhat_artwork 
redhat_menus htmlview 
redhat_menus desktop_printing 
redhat_menus control_center 
redhat_menus evolution 
redhat_menus gnome_desktop 
redhat_menus gnome_panel 
redhat_menus gnome_vfs2 
redhat_menus gthumb 
redhat_menus kdebase 
redhat_menus kdelibs 
redhat_menus nautilus 
redhat_menus openoffice.org 
redhat_menus xmms 
rhnlib up2date 
rhnlib rhn_applet 
rhpl system_config_mouse 
rhpl up2date 
rhpl system_config_network_tui 
rhpl anaconda 
rhpl authconfig_gtk 
rhpl booty 
rhpl firstboot 
rhpl system_config_boot 
rhpl system_config_date 
rhpl system_config_display 
rhpl system_config_keyboard 
rhpl system_config_kickstart 
rhpl system_config_language 
rhpl system_config_lvm 
rhpl system_config_netboot 
rhpl system_config_nfs 
rhpl system_config_packages 
rhpl system_config_printer 
rhpl system_config_rootpassword 
rhpl system_config_securitylevel 
rhpl system_config_services 
rhpl system_config_soundcard 
rmt dump 
rpm rpm_python 
rpm up2date 
rpm rpm_build 
rpm rpm_devel 
rpm_python up2date 
rpm_python system_config_network_tui 
rpm_python anaconda 
rpm_python anaconda_runtime 
rpm_python rhn_applet 
rpm_python system_config_packages 
ruby irb 
ruby_libs ruby 
ruby_libs ruby_devel 
ruby_libs ruby_tcltk 
samba samba_swat 
samba system_config_samba 
samba_common gnome_vfs2_smb 
samba_common samba 
samba_common samba_client 
sane_backends libsane_hpoj 
sane_backends sane_backends_devel 
sane_backends sane_frontends 
scrollkeeper file_roller 
scrollkeeper gedit 
scrollkeeper gnome_applets 
scrollkeeper gnome_user_docs 
scrollkeeper gok 
scrollkeeper evolution 
scrollkeeper ggv 
scrollkeeper gnome_games 
scrollkeeper gnome_media 
scrollkeeper gnomemeeting 
scrollkeeper gnome_panel 
scrollkeeper gnome_pilot 
scrollkeeper gthumb 
scrollkeeper nautilus 
scrollkeeper planner 
scrollkeeper yelp 
SDL kdeaddons 
SDL SDL_devel 
sed pam 
sed kbd 
sed sysreport 
sed nss_ldap 
sed nfs_utils 
sed sendmail 
sed a2ps 
sed autofs 
sed inn 
sed ntp 
sed samba 
sed xorg_x11_xfs 
selinux_policy_targeted selinux_policy_targeted_sources 
setools setools_gui 
setup filesystem 
setup basesystem 
setup initscripts 
setup dump 
setup sendmail 
setup xinetd 
setup postfix 
sgml_common docbook_slides 
sgml_common docbook_dtds 
sgml_common docbook_simple 
sgml_common docbook_style_dsssl 
sgml_common jadetex 
sgml_common openjade 
sgml_common psgml 
shadow_utils rpm 
shadow_utils lockdev 
shadow_utils slocate 
shadow_utils FreeWnn 
shadow_utils kdelibs 
shadow_utils mailman 
shadow_utils squid 
shadow_utils webalizer 
shadow_utils xorg_x11_xfs 
shared_mime_info gnome_vfs2 
shared_mime_info planner 
sip sip_devel 
sip_devel PyQt_devel 
slang newt 
slang slang_devel 
slang_devel newt_devel 
sox system_config_soundcard 
spamassassin evolution 
speex openh323 
speex speex_devel 
startup_notification gnome_desktop 
startup_notification libwnck 
startup_notification metacity 
startup_notification openoffice.org 
startup_notification startup_notification_devel 
startup_notification_devel gnome_desktop_devel 
subversion mod_dav_svn 
subversion subversion_devel 
subversion subversion_perl 
switchdesk switchdesk_gui 
switchdesk xinitrc 
sysfsutils sysfsutils_devel 
sysklogd initscripts 
sysklogd vixie_cron 
syslinux mkbootdisk 
syslinux system_config_netboot 
system_config_date firstboot 
system_config_display firstboot 
system_config_keyboard firstboot 
system_config_language firstboot 
system_config_language system_config_kickstart 
system_config_network firstboot 
system_config_network_tui system_config_network 
system_config_packages firstboot 
system_config_printer hal_cups_utils 
system_config_printer system_config_printer_gui 
system_config_rootpassword firstboot 
system_config_securitylevel firstboot 
system_config_securitylevel_tui system_config_securitylevel 
system_config_soundcard firstboot 
system_switch_mail system_switch_mail_gnome 
SysVinit initscripts 
tar mkinitrd 
tar amanda 
tcl dejagnu 
tcl isdn4k_utils_vboxgetty 
tcl postgresql_tcl 
tcl tcl_devel 
tcl tclx 
tcl tix 
tcl tk 
tclx tclx_devel 
tetex jadetex 
tetex passivetex 
tetex tetex_latex 
tetex_dvips docbook_utils 
tetex_dvips tetex_latex 
tetex_dvips tetex_xdvi 
tetex_fonts tetex 
tetex_fonts tetex_dvips 
tetex_latex linuxdoc_tools 
tetex_latex jadetex 
tetex_latex xmltex 
texinfo octave 
tftp_server system_config_netboot 
tix tix_devel 
tix tix_doc 
tk tclx 
tk tix 
tk tk_devel 
tkinter python_tools 
tmpwatch squirrelmail 
tmpwatch tetex 
transfig xfig 
ttfonts_ja VFlib2_conf_ja 
ttmkfdir fonts_xorg_truetype 
ttmkfdir ttfonts_ko 
tzdata glibc_common 
udev hal 
udev linuxwacom 
umb_scheme guile 
unixODBC freeradius_unixODBC 
unixODBC MyODBC 
unixODBC unixODBC_devel 
unixODBC unixODBC_kde 
unzip openoffice.org 
unzip xmms 
up2date firstboot 
up2date up2date_gnome 
up2date_gnome rhn_applet 
urw_fonts ghostscript 
urw_fonts libgnomeprint22 
urw_fonts xpdf 
usbutils hotplug 
usermode kbd 
usermode system_config_mouse 
usermode system_config_network_tui 
usermode system_config_httpd 
usermode gdm 
usermode hwbrowser 
usermode authconfig_gtk 
usermode ethereal_gnome 
usermode firstboot 
usermode kdeadmin 
usermode mtr_gtk 
usermode system_config_boot 
usermode system_config_date 
usermode system_config_display 
usermode system_config_keyboard 
usermode system_config_language 
usermode system_config_nfs 
usermode system_config_packages 
usermode system_config_printer 
usermode system_config_printer_gui 
usermode system_config_rootpassword 
usermode system_config_samba 
usermode system_config_securitylevel 
usermode system_config_services 
usermode system_config_soundcard 
usermode system_config_users 
usermode system_logviewer 
usermode up2date_gnome 
usermode usermode_gtk 
usermode_gtk system_config_services 
usermode_gtk up2date_gnome 
utempter gnome_libs 
utempter libgnome 
utempter xorg_x11 
util_linux hal 
util_linux initscripts 
util_linux prelink 
util_linux usermode 
util_linux portmap 
valgrind valgrind_callgrind 
VFlib2 ghostscript 
VFlib2 VFlib2_conf_ja 
VFlib2 VFlib2_devel 
VFlib2 VFlib2_VFjfm 
vim_common vim_enhanced 
vim_common vim_X11 
vim_minimal sudo 
vixie_cron mailman 
vixie_cron mrtg 
vte gnome_terminal 
vte vte_devel 
w3c_libwww w3c_libwww_apps 
w3c_libwww w3c_libwww_devel 
which docbook_utils 
which xinitrc 
wireless_tools NetworkManager 
x3270 x3270_text 
x3270 x3270_x11 
Xaw3d emacs 
Xaw3d Xaw3d_devel 
xdelta xdelta_devel 
xemacs xemacs_info 
xemacs_common xemacs_nox 
xemacs_common apel_xemacs 
xemacs_common xemacs 
xemacs_sumo xemacs_nox 
xemacs_sumo xemacs 
xemacs_sumo xemacs_sumo_el 
xinetd cups 
xinetd tftp_server 
xinetd finger_server 
xinetd amanda_client 
xinetd amanda_server 
xinetd samba_swat 
xinetd talk_server 
xinetd telnet_server 
xinitrc gdm 
xinitrc xorg_x11 
xinitrc xorg_x11_xdm 
xloadimage xscreensaver 
xml_common docbook_dtds 
xml_common docbook_dtds 
xml_common docbook_style_xsl 
xml_common xhtml1_dtds 
xmlsec1 xmlsec1_openssl 
xmlsec1 xmlsec1_devel 
xmlsec1 xmlsec1_openssl_devel 
xmlsec1_devel xmlsec1_openssl_devel 
xmlsec1_openssl xmlsec1_openssl_devel 
xmltex passivetex 
xmms xmms_flac 
xmms xmms_devel 
xmms xmms_skins 
xorg_x11 linuxwacom 
xorg_x11 xorg_x11_tools 
xorg_x11 xorg_x11_xdm 
xorg_x11 xorg_x11_Xdmx 
xorg_x11 xorg_x11_Xnest 
xorg_x11 xorg_x11_Xvfb 
xorg_x11_deprecated_libs xorg_x11_deprecated_libs_devel 
xorg_x11_deprecated_libs_devel openmotif_devel 
xorg_x11_devel openmotif_devel 
xorg_x11_devel qt_devel 
xorg_x11_devel Xaw3d_devel 
xorg_x11_devel xorg_x11_deprecated_libs_devel 
xorg_x11_libs pango 
xorg_x11_libs xorg_x11 
xorg_x11_libs xorg_x11_devel 
xorg_x11_libs xorg_x11_xfs 
xorg_x11_xfs xorg_x11 
xpdf xfig 
xscreensaver kdeartwork 
xscreensaver control_center 
xsri gdm 
xsri firstboot 
xsri system_config_display 
xterm xorg_x11_twm 
ypbind yp_tools 
yp_tools ypbind 
zip libgcj 
zip libgcj_devel 
zlib libtiff 
zlib emacs_nox 
zlib emacs 
zlib ghostscript 
zlib imlib 
zlib libmng 
zlib zlib_devel 
zlib_devel freetype_devel 
zlib_devel gcc_java 
zlib_devel ImageMagick_c++_devel 
zlib_devel ImageMagick_devel 
zlib_devel imlib_devel 
zlib_devel kdelibs_devel 
zlib_devel libgnome_devel 
zlib_devel libgnomeui_devel 
zlib_devel libpng10_devel 
zlib_devel libpng_devel 
zlib_devel libxml2_devel 
zlib_devel neon_devel 
zlib_devel openssl_devel 
zlib_devel w3c_libwww_devel 
zlib_devel xmlsec1_devel 
a2ps no_package 
acl no_package 
acpid no_package 
alchemist_devel no_package 
amanda_client no_package 
amanda_devel no_package 
amanda_server no_package 
am_utils no_package 
anaconda no_package 
anaconda_product no_package 
anaconda_runtime no_package 
anacron no_package 
apel no_package 
apmd no_package 
arptables_jf no_package 
arpwatch no_package 
ash no_package 
aspell_ca no_package 
aspell_cs no_package 
aspell_cy no_package 
aspell_da no_package 
aspell_de no_package 
aspell_el no_package 
aspell_es no_package 
aspell_fr no_package 
aspell_it no_package 
aspell_nl no_package 
aspell_no no_package 
aspell_pl no_package 
aspell_pt no_package 
aspell_sv no_package 
at no_package 
at_spi_devel no_package 
attr no_package 
audit no_package 
aumix no_package 
authd no_package 
autoconf213 no_package 
autofs no_package 
automake14 no_package 
automake15 no_package 
automake16 no_package 
automake17 no_package 
autorun no_package 
bc no_package 
beecrypt_devel no_package 
beecrypt_python no_package 
bg5ps no_package 
bind_chroot no_package 
bind_devel no_package 
bind_libs no_package 
bison no_package 
bitmap_fonts_cjk no_package 
bitstream_vera_fonts no_package 
blas no_package 
bluez_bluefw no_package 
bluez_hcidump no_package 
bluez_libs_devel no_package 
bluez_pin no_package 
bluez_utils no_package 
bluez_utils_cups no_package 
bogl_bterm no_package 
bogl_devel no_package 
boost_devel no_package 
bootparamd no_package 
bridge_utils no_package 
bridge_utils_devel no_package 
brltty no_package 
bug_buddy no_package 
busybox no_package 
busybox_anaconda no_package 
byacc no_package 
caching_nameserver no_package 
cadaver no_package 
Canna no_package 
Canna_devel no_package 
cdecl no_package 
cdparanoia no_package 
cdparanoia_devel no_package 
cdrecord_devel no_package 
ckermit no_package 
compat_db no_package 
compat_gcc_32_c++ no_package 
compat_glibc no_package 
compat_libcom_err no_package 
compat_libgcc_296 no_package 
compat_libstdc++_296 no_package 
compat_openldap no_package 
comps no_package 
cproto no_package 
crash no_package 
crypto_utils no_package 
cryptsetup no_package 
cscope no_package 
ctags no_package 
curl_devel no_package 
cvs no_package 
cyrus_imapd_devel no_package 
cyrus_imapd_murder no_package 
cyrus_imapd_nntp no_package 
cyrus_imapd_utils no_package 
cyrus_sasl_gssapi no_package 
cyrus_sasl_ntlm no_package 
cyrus_sasl_plain no_package 
cyrus_sasl_sql no_package 
dasher no_package 
db4_java no_package 
db4_tcl no_package 
db4_utils no_package 
ddd no_package 
dejagnu no_package 
desktop_backgrounds_extra no_package 
desktop_printing no_package 
dev86 no_package 
devhelp_devel no_package 
dhcp_devel no_package 
dhcpv6 no_package 
dhcpv6_client no_package 
dia no_package 
dietlibc no_package 
diffstat no_package 
diskdumputils no_package 
distcache_devel no_package 
dmalloc no_package 
dmraid no_package 
docbook_slides no_package 
docbook_utils_pdf no_package 
dos2unix no_package 
dovecot no_package 
doxygen_doxywizard no_package 
dtach no_package 
dump no_package 
dvd+rw_tools no_package 
ElectricFence no_package 
elfutils_devel no_package 
emacs no_package 
emacs_el no_package 
emacs_leim no_package 
emacs_nox no_package 
emacspeak no_package 
enscript no_package 
ethereal_gnome no_package 
evolution_connector no_package 
evolution_data_server_devel no_package 
evolution_devel no_package 
evolution_webcal no_package 
exim_doc no_package 
exim_mon no_package 
exim_sa no_package 
expect_devel no_package 
expectk no_package 
fbset no_package 
festival_devel no_package 
fetchmail no_package 
file_roller no_package 
finger no_package 
finger_server no_package 
firefox no_package 
firstboot no_package 
flac_devel no_package 
fonts_arabic no_package 
fonts_bengali no_package 
fonts_hebrew no_package 
fonts_ISO8859_2_100dpi no_package 
fonts_ISO8859_2 no_package 
fonts_ISO8859_2_75dpi no_package 
fonts_ja no_package 
fonts_KOI8_R_100dpi no_package 
fonts_KOI8_R no_package 
fonts_KOI8_R_75dpi no_package 
fonts_xorg_100dpi no_package 
fonts_xorg_base no_package 
fonts_xorg_cyrillic no_package 
fonts_xorg_ISO8859_14_100dpi no_package 
fonts_xorg_ISO8859_14_75dpi no_package 
fonts_xorg_ISO8859_15_100dpi no_package 
fonts_xorg_ISO8859_15_75dpi no_package 
fonts_xorg_ISO8859_2_100dpi no_package 
fonts_xorg_ISO8859_2_75dpi no_package 
fonts_xorg_ISO8859_9_100dpi no_package 
fonts_xorg_ISO8859_9_75dpi no_package 
fonts_xorg_syriac no_package 
fonts_xorg_truetype no_package 
freeglut_devel no_package 
freeradius_mysql no_package 
freeradius_postgresql no_package 
freeradius_unixODBC no_package 
freetype_demos no_package 
freetype_utils no_package 
FreeWnn no_package 
FreeWnn_devel no_package 
fribidi_devel no_package 
fsh no_package 
ftp no_package 
gaim no_package 
gamin_devel no_package 
gcc4_c++ no_package 
gcc4_gfortran no_package 
gcc_gnat no_package 
gcc_objc no_package 
gconf_editor no_package 
gdbm_devel no_package 
gdk_pixbuf_devel no_package 
gdm no_package 
gd_progs no_package 
gedit no_package 
gedit_devel no_package 
gettext_devel no_package 
gftp no_package 
ggv no_package 
ghostscript_devel no_package 
ghostscript_gtk no_package 
gimp_data_extras no_package 
gimp_devel no_package 
gimp_gap no_package 
gimp_help no_package 
gimp_print_cups no_package 
gimp_print_devel no_package 
gimp_print_plugin no_package 
gimp_print_utils no_package 
glade2 no_package 
glibc_kernheaders no_package 
glibc_profile no_package 
glibc_utils no_package 
gmp_devel no_package 
gnome_applets no_package 
gnome_audio no_package 
gnome_audio_extra no_package 
gnome_desktop_devel no_package 
gnome_games no_package 
gnome_kerberos no_package 
gnome_keyring_devel no_package 
gnome_keyring_manager no_package 
gnome_libs_devel no_package 
gnome_mag_devel no_package 
gnomemeeting no_package 
gnome_nettool no_package 
gnome_panel_devel no_package 
gnome_pilot_conduits no_package 
gnome_pilot_devel no_package 
gnome_python2_applet no_package 
gnome_python2_gconf no_package 
gnome_python2_gnomeprint no_package 
gnome_python2_gnomevfs no_package 
gnome_python2_nautilus no_package 
gnome_session no_package 
gnome_speech_devel no_package 
gnome_system_monitor no_package 
gnome_terminal no_package 
gnome_themes no_package 
gnome_user_docs no_package 
gnome_utils no_package 
gnopernicus no_package 
gnuplot_emacs no_package 
gnutls_devel no_package 
gok_devel no_package 
gpdf no_package 
gperf no_package 
gphoto2_devel no_package 
gpm_devel no_package 
groff_gxditview no_package 
groff_perl no_package 
grub no_package 
gsl_devel no_package 
gstreamer_plugins_devel no_package 
gstreamer_tools no_package 
gtk_doc no_package 
gtk_engines no_package 
gtkhtml2_devel no_package 
gtkspell_devel no_package 
guile_devel no_package 
h2ps no_package 
hal_devel no_package 
hal_gnome no_package 
hdparm no_package 
HelixPlayer no_package 
hesiod_devel no_package 
hpijs no_package 
hpoj_devel no_package 
htdig_web no_package 
httpd_manual no_package 
hwbrowser no_package 
icon_slicer no_package 
iiimf_docs no_package 
iiimf_emacs no_package 
iiimf_gnome_im_switcher no_package 
iiimf_gtk no_package 
iiimf_le_canna no_package 
iiimf_le_chinput no_package 
iiimf_le_hangul no_package 
iiimf_le_sun_thai no_package 
iiimf_le_unit no_package 
iiimf_le_xcin no_package 
iiimf_libs_devel no_package 
iiimf_x no_package 
ImageMagick_c++_devel no_package 
ImageMagick_perl no_package 
inn_devel no_package 
ipsec_tools no_package 
iptables_devel no_package 
iptables_ipv6 no_package 
iptraf no_package 
iptstate no_package 
iputils no_package 
irb no_package 
irda_utils no_package 
isdn4k_utils_devel no_package 
isdn4k_utils_vboxgetty no_package 
java_1.4.2_gcj_compat_devel no_package 
jisksp14 no_package 
jisksp16_1990 no_package 
joe no_package 
jpackage_utils no_package 
jwhois no_package 
k3b no_package 
kappa20 no_package 
katana_build no_package 
kbd no_package 
kdbg no_package 
kdeaddons_atlantikdesigner no_package 
kdeaddons_xmms no_package 
kdeadmin no_package 
kdeartwork_icons no_package 
kdegames_devel no_package 
kdegraphics_devel no_package 
kde_i18n_Bengali no_package 
kde_i18n_Brazil no_package 
kde_i18n_British no_package 
kde_i18n_Bulgarian no_package 
kde_i18n_Catalan no_package 
kde_i18n_Chinese no_package 
kde_i18n_Chinese_Big5 no_package 
kde_i18n_Czech no_package 
kde_i18n_Danish no_package 
kde_i18n_Dutch no_package 
kde_i18n_Estonian no_package 
kde_i18n_Finnish no_package 
kde_i18n_French no_package 
kde_i18n_German no_package 
kde_i18n_Greek no_package 
kde_i18n_Hebrew no_package 
kde_i18n_Hindi no_package 
kde_i18n_Hungarian no_package 
kde_i18n_Icelandic no_package 
kde_i18n_Italian no_package 
kde_i18n_Japanese no_package 
kde_i18n_Norwegian no_package 
kde_i18n_Norwegian_Nynorsk no_package 
kde_i18n_Polish no_package 
kde_i18n_Portuguese no_package 
kde_i18n_Punjabi no_package 
kde_i18n_Romanian no_package 
kde_i18n_Russian no_package 
kde_i18n_Serbian no_package 
kde_i18n_Slovak no_package 
kde_i18n_Slovenian no_package 
kde_i18n_Spanish no_package 
kde_i18n_Swedish no_package 
kde_i18n_Tamil no_package 
kde_i18n_Turkish no_package 
kde_i18n_Ukrainian no_package 
kdemultimedia_devel no_package 
kdenetwork_devel no_package 
kdenetwork_nowlistening no_package 
kdepim_devel no_package 
kdesdk_devel no_package 
kdeutils_devel no_package 
kdevelop no_package 
kernel_devel no_package 
kernel_doc no_package 
kernel_hugemem no_package 
kernel_hugemem_devel no_package 
kernel_smp no_package 
kernel_smp_devel no_package 
kinput2 no_package 
knm_new no_package 
kon2 no_package 
kon2_fonts no_package 
krb5_auth_dialog no_package 
krb5_server no_package 
krb5_workstation no_package 
krbafs_devel no_package 
krbafs_utils no_package 
kudzu_devel no_package 
lam no_package 
lapack no_package 
lftp no_package 
lha no_package 
libacl_devel no_package 
libao_devel no_package 
libavc1394_devel no_package 
libcap_devel no_package 
libc_client_devel no_package 
libdbi_dbd_mysql no_package 
libdbi_dbd_pgsql no_package 
libdbi_devel no_package 
libdv_devel no_package 
libdv_tools no_package 
libgcrypt_devel no_package 
libgnomecups_devel no_package 
libgtop2_devel no_package 
libmng_static no_package 
libmudflap_devel no_package 
libmusicbrainz_devel no_package 
libpng10_devel no_package 
libsane_hpoj no_package 
libselinux_devel no_package 
libsepol_devel no_package 
libsilc_devel no_package 
libsilc_doc no_package 
libtabe_devel no_package 
libtheora_devel no_package 
libtool no_package 
libungif_progs no_package 
libuser_devel no_package 
libwmf_devel no_package 
libwvstreams_devel no_package 
libxklavier_devel no_package 
libxslt_python no_package 
lilo no_package 
linuxdoc_tools no_package 
linuxwacom_devel no_package 
lm_sensors_devel no_package 
lockdev_devel no_package 
logwatch no_package 
lrzsz no_package 
lslk no_package 
lsof no_package 
ltrace no_package 
lynx no_package 
mailman no_package 
man no_package 
man_pages no_package 
man_pages_cs no_package 
man_pages_da no_package 
man_pages_de no_package 
man_pages_es no_package 
man_pages_fr no_package 
man_pages_it no_package 
man_pages_ja no_package 
man_pages_ko no_package 
man_pages_pl no_package 
man_pages_ru no_package 
mc no_package 
mdadm no_package 
memtest86+ no_package 
mgetty_sendfax no_package 
mgetty_viewfax no_package 
mgetty_voice no_package 
mikmod_devel no_package 
miniChinput no_package 
minicom no_package 
mkbootdisk no_package 
mod_auth_kerb no_package 
mod_auth_mysql no_package 
mod_auth_pgsql no_package 
mod_authz_ldap no_package 
mod_dav_svn no_package 
mod_perl_devel no_package 
mod_python no_package 
mod_ssl no_package 
mozilla_chat no_package 
mozilla_devel no_package 
mozilla_dom_inspector no_package 
mozilla_js_debugger no_package 
mozilla_mail no_package 
mrtg no_package 
mtr_gtk no_package 
mt_st no_package 
mtx no_package 
mutt no_package 
MyODBC no_package 
mysql_bench no_package 
mysqlclient10_devel no_package 
mysql_devel no_package 
MySQL_python no_package 
mysql_server no_package 
nabi no_package 
nano no_package 
nasm no_package 
nasm_doc no_package 
nasm_rdoff no_package 
nautilus_cd_burner_devel no_package 
nautilus_media no_package 
nc no_package 
ncompress no_package 
nedit no_package 
neon_devel no_package 
netconfig no_package 
netdump no_package 
netdump_server no_package 
netpbm_devel no_package 
net_snmp_devel no_package 
net_snmp_libs no_package 
net_snmp_perl no_package 
NetworkManager_gnome no_package 
newt_devel no_package 
nhpf no_package 
nmap_frontend no_package 
nptl_devel no_package 
nptl_devel no_package 
nss_db_compat no_package 
nss_ldap no_package 
ntsysv no_package 
numactl no_package 
octave no_package 
octave_devel no_package 
open no_package 
openh323_devel no_package 
openjade_devel no_package 
openldap_clients no_package 
openldap_servers_sql no_package 
openmotif21 no_package 
openmotif_devel no_package 
openoffice.org_i18n no_package 
openoffice.org_kde no_package 
openssh_askpass no_package 
openssh_askpass_gnome no_package 
openssl096b no_package 
openssl_perl no_package 
oprofile_devel no_package 
pam_ccreds no_package 
pam_devel no_package 
pam_krb5 no_package 
pam_passwdqc no_package 
pam_smb no_package 
parted_devel no_package 
patchutils no_package 
pax no_package 
pcmcia_cs no_package 
pdksh no_package 
perl_Bit_Vector no_package 
perl_Crypt_SSLeay no_package 
perl_DateManip no_package 
perl_DBD_Pg no_package 
perl_Digest_HMAC no_package 
perl_Digest_SHA1 no_package 
perl_Filter no_package 
perl_LDAP no_package 
perl_Net_DNS no_package 
perl_suidperl no_package 
perl_Time_HiRes no_package 
perl_XML_Grove no_package 
perl_XML_LibXML no_package 
perl_XML_Twig no_package 
php_devel no_package 
php_domxml no_package 
php_gd no_package 
php_imap no_package 
php_ldap no_package 
php_mbstring no_package 
php_mysql no_package 
php_ncurses no_package 
php_odbc no_package 
php_pgsql no_package 
php_snmp no_package 
php_xmlrpc no_package 
pinfo no_package 
planner no_package 
pmake no_package 
postfix no_package 
postfix_pflogsumm no_package 
postgresql_contrib no_package 
postgresql_devel no_package 
postgresql_docs no_package 
postgresql_jdbc no_package 
postgresql_odbc no_package 
postgresql_pl no_package 
postgresql_python no_package 
postgresql_tcl no_package 
postgresql_test no_package 
prelink no_package 
procps no_package 
psacct no_package 
psgml no_package 
pstack no_package 
pump_devel no_package 
pvm_gui no_package 
pygtk2_devel no_package 
pyorbit_devel no_package 
PyQt_devel no_package 
PyQt_examples no_package 
Pyrex no_package 
python_docs no_package 
python_ldap no_package 
python_tools no_package 
qt_config no_package 
qt_MySQL no_package 
qt_ODBC no_package 
qt_PostgreSQL no_package 
quagga no_package 
quagga_contrib no_package 
quagga_devel no_package 
quota no_package 
radvd no_package 
rcs no_package 
rdate no_package 
rdist no_package 
redhat_lsb no_package 
redhat_release no_package 
redhat_rpm_config no_package 
rhdb_utils no_package 
rhgb no_package 
rhn_applet no_package 
rhythmbox no_package 
rootfiles no_package 
rpm_build no_package 
rpmdb_redhat no_package 
rpm_devel no_package 
rpm_libs no_package 
rp_pppoe no_package 
rsh no_package 
rsh_server no_package 
rsync no_package 
ruby_devel no_package 
ruby_docs no_package 
ruby_mode no_package 
ruby_tcltk no_package 
rusers no_package 
rusers_server no_package 
rwho no_package 
samba_client no_package 
samba_swat no_package 
sane_backends_devel no_package 
sane_frontends no_package 
schedutils no_package 
screen no_package 
SDL_devel no_package 
selinux_doc no_package 
selinux_policy_targeted_sources no_package 
sendmail no_package 
sendmail_cf no_package 
sendmail_devel no_package 
sendmail_doc no_package 
setarch no_package 
setools_gui no_package 
setserial no_package 
setuptool no_package 
sg3_utils no_package 
sharutils no_package 
skkdic no_package 
skkinput no_package 
slocate no_package 
sound_juicer no_package 
sox_devel no_package 
specspo no_package 
speex_devel no_package 
splint no_package 
squid no_package 
squirrelmail no_package 
star no_package 
statserial no_package 
strace no_package 
stunnel no_package 
subversion_devel no_package 
subversion_perl no_package 
sudo no_package 
swig no_package 
switchdesk_gui no_package 
symlinks no_package 
synaptics no_package 
sysfsutils_devel no_package 
sysreport no_package 
sysstat no_package 
system_config_boot no_package 
system_config_httpd no_package 
system_config_kickstart no_package 
system_config_lvm no_package 
system_config_mouse no_package 
system_config_netboot no_package 
system_config_nfs no_package 
system_config_printer_gui no_package 
system_config_samba no_package 
system_config_services no_package 
system_config_users no_package 
system_logviewer no_package 
system_switch_im no_package 
system_switch_mail_gnome no_package 
taipeifonts no_package 
talk no_package 
talk_server no_package 
tcl_devel no_package 
tcl_html no_package 
tclx_devel no_package 
tclx_doc no_package 
tcpdump no_package 
tcp_wrappers no_package 
tcsh no_package 
telnet no_package 
telnet_server no_package 
termcap no_package 
tetex_afm no_package 
tetex_doc no_package 
tetex_xdvi no_package 
tftp no_package 
theora_tools no_package 
thunderbird no_package 
time no_package 
tix_devel no_package 
tix_doc no_package 
tk_devel no_package 
tn5250 no_package 
tn5250_devel no_package 
tora no_package 
traceroute no_package 
tsclient no_package 
ttfonts_bn no_package 
ttfonts_gu no_package 
ttfonts_hi no_package 
ttfonts_ko no_package 
ttfonts_pa no_package 
ttfonts_ta no_package 
ttfonts_zh_CN no_package 
ttfonts_zh_TW no_package 
ttfprint no_package 
tux no_package 
units no_package 
unix2dos no_package 
unixODBC_devel no_package 
unixODBC_kde no_package 
uucp no_package 
valgrind_callgrind no_package 
vconfig no_package 
VFlib2_conf_ja no_package 
VFlib2_devel no_package 
VFlib2_VFjfm no_package 
vim_enhanced no_package 
vim_X11 no_package 
vino no_package 
vlock no_package 
vnc no_package 
vnc_server no_package 
vorbis_tools no_package 
vsftpd no_package 
vte_devel no_package 
w3c_libwww_apps no_package 
w3c_libwww_devel no_package 
webalizer no_package 
wget no_package 
words no_package 
wvdial no_package 
x3270_text no_package 
x3270_x11 no_package 
Xaw3d_devel no_package 
xcdroast no_package 
xchat no_package 
xcin no_package 
xdelta_devel no_package 
xemacs_el no_package 
xemacs_info no_package 
xemacs_nox no_package 
xemacs_sumo_el no_package 
xemacs_sumo_info no_package 
xfig no_package 
xhtml1_dtds no_package 
xisdnload no_package 
xmlsec1_openssl_devel no_package 
xmlto no_package 
xmms_devel no_package 
xmms_flac no_package 
xmms_skins no_package 
xojpanel no_package 
xorg_x11_doc no_package 
xorg_x11_font_utils no_package 
xorg_x11_Mesa_libGL no_package 
xorg_x11_Mesa_libGLU no_package 
xorg_x11_sdk no_package 
xorg_x11_tools no_package 
xorg_x11_twm no_package 
xorg_x11_xauth no_package 
xorg_x11_xdm no_package 
xorg_x11_Xdmx no_package 
xorg_x11_Xnest no_package 
xorg_x11_Xvfb no_package 
xrestop no_package 
xsane no_package 
xsane_gimp no_package 
yelp no_package 
ypserv no_package 
zisofs_tools no_package 
zsh no_package 
zsh_html no_package 
EOF
tmp=$(echo $1|tr "-" "_")
sed "/\<$tmp\>/!d" $TEMP
