#!/usr/bin/perl


foreach (<DATA>)
{
}
__DATA__

gameupdate_bt
rich_ntfs_lib
ww_netdisk
rich_common_lib
rich_register
rich_octopus3
rich_netclone2
remote_manager_system
richdlxp_cp
diskless_clntools
rich_manager
anti_arp_attack
dlxp_bootldr
io_device_manager
ww_btupdate
industry_addition
rich_servercontrol
rich_gpxe
personal_disk
rt_gameupdate_bt
dlxp_help
police_login
ww_gmclient
rich_test_docs
rich_protect
dlxp_windrv
web_office
ww_frameman
virtual_desk_system
ww_gamesync
web_gamemenu
hp_register
remote_manager_system__copy_
rich_addvalue
dos_hotbackup
training
ww_netclone
octopus_svdisk
web_daohang
ww_gamemenu
richdlxp
rich_bt2
netware_emulator
web_register
diskless_clntools2
rich_octopus
diskless_rich
remote_tool
bt2_client
rich_rms
web_richtech
richcgo
ww_secucenter
fulldisk
ww_interface
data_collecting
reg_system_srv
web_richbar
richgau10
rich_addvalue2
super_cgo
rich_ad_system
rich_doc_collaboration
diskless_linux
rich_octopus3x
dos_menu
ww_centmanager
stock_info
dlxp_tools
bt_vdisk_drv
dev_ctrl_interface
rich_manager_cp
rich_backup
diskless_oem
dlxp_founder
web_cs




#==========================================================================
diskless_rich_536
richdlxp_cp
dlxp_bootldr
io_device_manager
rich_servercontrol
richdlxp4
dlxp_windrv
dlxp_bootldr_asua_26
virtual_desk_system
web_gamemenu
ww_netclone
ww_gamemenu
rich_bt2
netware_emulator
data_collecting
rich_addvalue2
diskless_rich_zjl
rich_ad_system
diskless_rich_687
rich_backup

#==========================================================================
storage
eschoolbag
tvm4
rsctl-center
serviceenabler
eschoolbag_svn
alligator
vdi
servicemanagement


#==========================================================================
11698666_v2
petty_china_new
xboot3
petty_new_site
file_explorer_manager_web_index
foreign_trade_management_sys
home_234_profile
sino_pet
qianlong_webadmin_v2
petty_china
11698666


#==========================================================================
PartImage
RealMonitor
_pre_cache
aix_ibm_cli_usage
bin
daemon_monitor
develop_bash
develop_sed_txt_tools
develop_cpp
develop_ddk
develop_reg_register_bak
develop_etc
develop_kernel
develop_mfc
develop_network
develop_perl
develop_perl_windows
develop_php
develop_python
develop_qemu_kvm
develop_thread
develop_wxwidgets
develop_wxwidgets_73
develop_xxunit
doc
doc_collaboration_tnsoft
global-4.4_logger
include_structs_code_generator
iso_index_and_search
linux
linux2
lmyunit
logtrans_srv_new_v5
math_tools_v2
myproject
netware_emulator_73_1159
netware_emulator_f8_1163
netware_emulator_rich_1090
octopus_agile
old
pkg_develop
project_collaboration
qzjProject
random_things_v3
rich3_1_262
richtech-scripts_rpm
structs_code_generator
svn_merge_tools
svn_trunk_tags_branches
sync
system_initialization_win
test
vdisk_tcp_client
vim_common
volume_shadow_tools
