#!/usr/bin/perl
foreach (<DATA>)
{
	print $_;
}
__DATA__

 pip install XStatic
 pip install XStatic-AdminLTE
 pip install XStatic-Angular
 pip install XStatic-Angular-Animate
 pip install XStatic-Angular-Bootstrap
 pip install XStatic-Angular-Cookies
 pip install XStatic-Angular-FileUpload
 pip install XStatic-Angular-Gettext
 pip install XStatic-Angular-IrDragNDrop
 pip install XStatic-Angular-lrdragndrop
 pip install XStatic-Angular-Mock
 pip install XStatic-Angular-nvd3
 pip install XStatic-Angular-Sanitize
 pip install XStatic-Angular-Schema-Form
 pip install XStatic-Angular-Schema-Form-Bootstrap
 pip install XStatic-angular-ui
 pip install XStatic-angular-ui-router
 pip install XStatic-AnyWikiDraw
 pip install XStatic-autosize
 pip install XStatic-Bootbox
 pip install XStatic-Bootstrap
 pip install XStatic-Bootstrap-Datepicker
 pip install XStatic-BootstrapOverflowNavs
 pip install XStatic-Bootstrap-SCSS
 pip install XStatic-BootstrapTags
 pip install XStatic-BootstrapTagsInput
 pip install XStatic-bootswatch
 pip install XStatic-browser-update
 pip install XStatic-Chart.js
 pip install XStatic-ChartNew.js
 pip install XStatic-Chosen
 pip install XStatic-CKEditor
 pip install XStatic-D3
 pip install XStatic-D32
 pip install XStatic-DataTables
 pip install XStatic-ExtJS
 pip install XStatic-Font-Awesome
 pip install XStatic-fullcalendar
 pip install XStatic-Hogan
 pip install XStatic-html5shiv
 pip install XStatic-Jasmine
 pip install XStatic-jQuery
 pip install XStatic-JQuery.Bootstrap.Wizard
 pip install XStatic-jQuery-File-Upload
 pip install XStatic-JQuery-Migrate
 pip install XStatic-JQuery.quicksearch
 pip install XStatic-JQuery.TableSorter
 pip install XStatic-jquery-ui
 pip install XStatic-jReject
 pip install XStatic-JSEncrypt
 pip install XStatic-JSON-js
 pip install XStatic-less
 pip install XStatic-lodash
 pip install XStatic-Magic-Search
 pip install XStatic-MarkitUp
 pip install XStatic-MathJax
 pip install XStatic-mdi
 pip install XStatic-moment
 pip install XStatic-multiDownload
 pip install XStatic-NVD3
 pip install XStatic-objectpath
 pip install XStatic-Pygments
 pip install XStatic-QUnit
 pip install XStatic-React
 pip install XStatic-RequireJS
 pip install XStatic-Rickshaw
 pip install XStatic-roboto-fontface
 pip install XStatic-smart-table
 pip install XStatic-socialshareprivacy
 pip install XStatic-Spin
 pip install XStatic-svg-edit-moin
 pip install XStatic-svgweb
 pip install XStatic-Tablesorter-Mottie
 pip install XStatic-term.js
 pip install XStatic-tv4
 pip install XStatic-TWikiDraw-moin
 pip install XStatic-underscore
